In [55]:
import fastf1
import psycopg
import json

In [74]:
database_url = "postgresql://formula_one:formula_one@127.0.0.1:5434/formula_one"

In [77]:
# fastf1.Cache.clear_cache()

In [78]:
session = fastf1.get_session(2026, 1, 1)
session.load(weather=True, laps=True, messages=True)
session

core           INFO 	Loading data for Australian Grand Prix - Practice 1 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 14
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 14)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']

2026 Season Round 1: Australian Grand Prix - Practice 1

In [81]:
def prepare_session(year, rd, s, session_obj):
    output = {}
    output['session_id'] = f'Y{year}R{rd:02d}S{s}'
    output['year'] = year
    output['round_number'] = rd
    output['session_number'] = s
    output['event_name'] = session_obj.session_info['Meeting']['Name']
    output['is_testing'] = False
    output['session_name'] = session_obj.name
    output['session_info'] = session_obj.session_info
    output['event_info'] = session_obj.event.to_dict()
    output['start_time'] = session_obj.session_start_time.total_seconds()
    output['t0_date'] = session_obj.t0_date
    output['total_laps'] = session_obj.total_laps

    for col in ["session_info", "event_info"]:
        output[col] = json.dumps(output[col], default=str)

    columns = list(output.keys())
    query = "insert into race_session ( {} ) values ( {} )".format(
        ",".join(columns),
        ",".join(["%s"] * len(columns))
    )
    with psycopg.connect(database_url) as conn:
        with conn.cursor() as cur:
            cur.execute(query, [output[c] for c in columns])
            conn.commit()


    return output

In [82]:
for year in [2026]:
    for rd in range(1, 6):
        for s in range(1, 6):
            session = fastf1.get_session(year, rd, s)
            session.load()
            id_ = f'Y{year}R{rd:02d}S{s}'
            prepare_session(year, rd, s, session)

core           INFO 	Loading data for Australian Grand Prix - Practice 1 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 14
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 14)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Australian Grand Prix - Practice 2 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Australian Grand Prix - Practice 3 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 18
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 18
core        WARNING 	No lap data for driver 55
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '6', '16', '81', '1', '44', '30', '41', '5', '27', '87', '31', '10', '23', '43', '14', '11', '77', '18', '3', '55']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 81
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']
core           INFO 	Loading data for Chinese Grand Prix - Practice 1 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Chinese Grand Prix - Sprint Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core        WARNING 	Sprint Qualifying is not supported by Ergast! Limited results are calculated from timing data.
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 11
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 11)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '1', '44', '81', '16', '10', '3', '87', '6', '27', '31', '30', '5', '41', '43', '55', '23', '14', '18', '77', '11']
core           INFO 	Loading data for Chinese Grand Prix - Sprint [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 63 completed the race distance 00:00.009000 before the recorded end of the session.
core           INFO 	Finished loading data for 22 drivers: ['63', '16', '44', '1', '12', '81', '30', '87', '3', '31', '10', '55', '5', '43', '6', '23', '14', '18', '11', '27', '77', '41']
core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '44', '16', '81', '1', '10', '3', '6', '87', '27', '43', '31', '30', '41', '5', '55', '23', '14', '77', '18', '11']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core        WARNING 	Driver 12 completed the race distance 00:00.022000 before the recorded end of the session.
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '44', '16', '87', '10', '30', '6', '55', '43', '27', '41', '77', '31', '11', '3', '14', '18', '81', '1', '5', '23']
core           INFO 	Loading data for Japanese Grand Prix - Practice 1 [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '16', '18', '23', '27', '30', '31', '34', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Japanese Grand Prix - Practice 2 [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Japanese Grand Prix - Practice 3 [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
_api        WARNING 	Driver 30: Encountered 1 timing integrity error(s) near lap(s): [17].
This might be a bug and should be reported.
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Driver 30: Lap timing integrity check failed for 1 lap(s)
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '81', '16', '1', '44', '10', '6', '5', '41', '3', '31', '27', '30', '43', '55', '23', '87', '11', '77', '14', '18']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.1]

In [85]:
session.results.head().T

,12,44,3,16,6
DriverNumber,12,44,3,16,6
BroadcastName,K ANTONELLI,L HAMILTON,M VERSTAPPEN,C LECLERC,I HADJAR
Abbreviation,ANT,HAM,VER,LEC,HAD
DriverId,antonelli,hamilton,max_verstappen,leclerc,hadjar
TeamName,Mercedes,Ferrari,Red Bull Racing,Ferrari,Red Bull Racing
TeamColor,00D7B6,ED1131,4781D7,ED1131,4781D7
TeamId,mercedes,ferrari,red_bull,ferrari,red_bull
FirstName,Kimi,Lewis,Max,Charles,Isack
LastName,Antonelli,Hamilton,Verstappen,Leclerc,Hadjar
FullName,Kimi Antonelli,Lewis Hamilton,Max Verstappen,Charles Leclerc,Isack Hadjar
HeadshotUrl,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...
CountryCode,,,,,
Position,1.0,2.0,3.0,4.0,5.0
ClassifiedPosition,1,2,3,4,5
GridPosition,2.0,5.0,6.0,8.0,7.0
Q1,NaT,NaT,NaT,NaT,NaT
Q2,NaT,NaT,NaT,NaT,NaT
Q3,NaT,NaT,NaT,NaT,NaT
Time,0 days 01:28:15.758000,0 days 00:00:10.768000,0 days 00:00:11.276000,0 days 00:00:44.151000,0 days 00:00:05.033000
Status,Finished,Finished,Finished,Finished,Lapped
Points,25.0,18.0,15.0,12.0,10.0
Laps,68.0,68.0,68.0,68.0,67.0

In [87]:
session.results.to_dict(orient='records')

[{'DriverNumber': '12',
  'BroadcastName': 'K ANTONELLI',
  'Abbreviation': 'ANT',
  'DriverId': 'antonelli',
  'TeamName': 'Mercedes',
  'TeamColor': '00D7B6',
  'TeamId': 'mercedes',
  'FirstName': 'Kimi',
  'LastName': 'Antonelli',
  'FullName': 'Kimi Antonelli',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/K/ANDANT01_Kimi_Antonelli/andant01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 1.0,
  'ClassifiedPosition': '1',
  'GridPosition': 2.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 01:28:15.758000'),
  'Status': 'Finished',
  'Points': 25.0,
  'Laps': 68.0},
 {'DriverNumber': '44',
  'BroadcastName': 'L HAMILTON',
  'Abbreviation': 'HAM',
  'DriverId': 'hamilton',
  'TeamName': 'Ferrari',
  'TeamColor': 'ED1131',
  'TeamId': 'ferrari',
  'FirstName': 'Lewis',
  'LastName': 'Hamilton',
  'FullName': 'Lewis Hamilton',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 2.0,
  'ClassifiedPosition': '2',
  'GridPosition': 5.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:00:10.768000'),
  'Status': 'Finished',
  'Points': 18.0,
  'Laps': 68.0},
 {'DriverNumber': '3',
  'BroadcastName': 'M VERSTAPPEN',
  'Abbreviation': 'VER',
  'DriverId': 'max_verstappen',
  'TeamName': 'Red Bull Racing',
  'TeamColor': '4781D7',
  'TeamId': 'red_bull',
  'FirstName': 'Max',
  'LastName': 'Verstappen',
  'FullName': 'Max Verstappen',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 3.0,
  'ClassifiedPosition': '3',
  'GridPosition': 6.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:00:11.276000'),
  'Status': 'Finished',
  'Points': 15.0,
  'Laps': 68.0},
 {'DriverNumber': '16',
  'BroadcastName': 'C LECLERC',
  'Abbreviation': 'LEC',
  'DriverId': 'leclerc',
  'TeamName': 'Ferrari',
  'TeamColor': 'ED1131',
  'TeamId': 'ferrari',
  'FirstName': 'Charles',
  'LastName': 'Leclerc',
  'FullName': 'Charles Leclerc',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 4.0,
  'ClassifiedPosition': '4',
  'GridPosition': 8.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:00:44.151000'),
  'Status': 'Finished',
  'Points': 12.0,
  'Laps': 68.0},
 {'DriverNumber': '6',
  'BroadcastName': 'I HADJAR',
  'Abbreviation': 'HAD',
  'DriverId': 'hadjar',
  'TeamName': 'Red Bull Racing',
  'TeamColor': '4781D7',
  'TeamId': 'red_bull',
  'FirstName': 'Isack',
  'LastName': 'Hadjar',
  'FullName': 'Isack Hadjar',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/I/ISAHAD01_Isack_Hadjar/isahad01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 5.0,
  'ClassifiedPosition': '5',
  'GridPosition': 7.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:00:05.033000'),
  'Status': 'Lapped',
  'Points': 10.0,
  'Laps': 67.0},
 {'DriverNumber': '43',
  'BroadcastName': 'F COLAPINTO',
  'Abbreviation': 'COL',
  'DriverId': 'colapinto',
  'TeamName': 'Alpine',
  'TeamColor': '00A1E8',
  'TeamId': 'alpine',
  'FirstName': 'Franco',
  'LastName': 'Colapinto',
  'FullName': 'Franco Colapinto',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/F/FRACOL01_Franco_Colapinto/fracol01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 6.0,
  'ClassifiedPosition': '6',
  'GridPosition': 10.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:00:19.510000'),
  'Status': 'Lapped',
  'Points': 8.0,
  'Laps': 67.0},
 {'DriverNumber': '30',
  'BroadcastName': 'L LAWSON',
  'Abbreviation': 'LAW',
  'DriverId': 'lawson',
  'TeamName': 'Racing Bulls',
  'TeamColor': '6C98FF',
  'TeamId': 'rb',
  'FirstName': 'Liam',
  'LastName': 'Lawson',
  'FullName': 'Liam Lawson',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LIALAW01_Liam_Lawson/lialaw01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 7.0,
  'ClassifiedPosition': '7',
  'GridPosition': 12.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:00:34.235000'),
  'Status': 'Lapped',
  'Points': 6.0,
  'Laps': 67.0},
 {'DriverNumber': '10',
  'BroadcastName': 'P GASLY',
  'Abbreviation': 'GAS',
  'DriverId': 'gasly',
  'TeamName': 'Alpine',
  'TeamColor': '00A1E8',
  'TeamId': 'alpine',
  'FirstName': 'Pierre',
  'LastName': 'Gasly',
  'FullName': 'Pierre Gasly',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/P/PIEGAS01_Pierre_Gasly/piegas01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 8.0,
  'ClassifiedPosition': '8',
  'GridPosition': 14.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:00:34.572000'),
  'Status': 'Lapped',
  'Points': 4.0,
  'Laps': 67.0},
 {'DriverNumber': '55',
  'BroadcastName': 'C SAINZ',
  'Abbreviation': 'SAI',
  'DriverId': 'sainz',
  'TeamName': 'Williams',
  'TeamColor': '1868DB',
  'TeamId': 'williams',
  'FirstName': 'Carlos',
  'LastName': 'Sainz',
  'FullName': 'Carlos Sainz',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 9.0,
  'ClassifiedPosition': '9',
  'GridPosition': 15.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:00:58.014000'),
  'Status': 'Lapped',
  'Points': 2.0,
  'Laps': 67.0},
 {'DriverNumber': '87',
  'BroadcastName': 'O BEARMAN',
  'Abbreviation': 'BEA',
  'DriverId': 'bearman',
  'TeamName': 'Haas F1 Team',
  'TeamColor': '9C9FA2',
  'TeamId': 'haas',
  'FirstName': 'Oliver',
  'LastName': 'Bearman',
  'FullName': 'Oliver Bearman',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OLIBEA01_Oliver_Bearman/olibea01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 10.0,
  'ClassifiedPosition': '10',
  'GridPosition': 16.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:00:59.049000'),
  'Status': 'Lapped',
  'Points': 1.0,
  'Laps': 67.0},
 {'DriverNumber': '81',
  'BroadcastName': 'O PIASTRI',
  'Abbreviation': 'PIA',
  'DriverId': 'piastri',
  'TeamName': 'McLaren',
  'TeamColor': 'F47600',
  'TeamId': 'mclaren',
  'FirstName': 'Oscar',
  'LastName': 'Piastri',
  'FullName': 'Oscar Piastri',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OSCPIA01_Oscar_Piastri/oscpia01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 11.0,
  'ClassifiedPosition': '11',
  'GridPosition': 4.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:00:12.699000'),
  'Status': 'Lapped',
  'Points': 0.0,
  'Laps': 66.0},
 {'DriverNumber': '27',
  'BroadcastName': 'N HULKENBERG',
  'Abbreviation': 'HUL',
  'DriverId': 'hulkenberg',
  'TeamName': 'Audi',
  'TeamColor': 'F50537',
  'TeamId': 'audi',
  'FirstName': 'Nico',
  'LastName': 'Hulkenberg',
  'FullName': 'Nico Hulkenberg',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/N/NICHUL01_Nico_Hulkenberg/nichul01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 12.0,
  'ClassifiedPosition': '12',
  'GridPosition': 11.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:00:14.182000'),
  'Status': 'Lapped',
  'Points': 0.0,
  'Laps': 66.0},
 {'DriverNumber': '5',
  'BroadcastName': 'G BORTOLETO',
  'Abbreviation': 'BOR',
  'DriverId': 'bortoleto',
  'TeamName': 'Audi',
  'TeamColor': 'F50537',
  'TeamId': 'audi',
  'FirstName': 'Gabriel',
  'LastName': 'Bortoleto',
  'FullName': 'Gabriel Bortoleto',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GABBOR01_Gabriel_Bortoleto/gabbor01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 13.0,
  'ClassifiedPosition': '13',
  'GridPosition': 13.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:00:21.156000'),
  'Status': 'Lapped',
  'Points': 0.0,
  'Laps': 66.0},
 {'DriverNumber': '31',
  'BroadcastName': 'E OCON',
  'Abbreviation': 'OCO',
  'DriverId': 'ocon',
  'TeamName': 'Haas F1 Team',
  'TeamColor': '9C9FA2',
  'TeamId': 'haas',
  'FirstName': 'Esteban',
  'LastName': 'Ocon',
  'FullName': 'Esteban Ocon',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/E/ESTOCO01_Esteban_Ocon/estoco01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 14.0,
  'ClassifiedPosition': '14',
  'GridPosition': 17.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:01:08.635000'),
  'Status': 'Lapped',
  'Points': 0.0,
  'Laps': 66.0},
 {'DriverNumber': '18',
  'BroadcastName': 'L STROLL',
  'Abbreviation': 'STR',
  'DriverId': 'stroll',
  'TeamName': 'Aston Martin',
  'TeamColor': '229971',
  'TeamId': 'aston_martin',
  'FirstName': 'Lance',
  'LastName': 'Stroll',
  'FullName': 'Lance Stroll',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 15.0,
  'ClassifiedPosition': '15',
  'GridPosition': 22.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:00:18.397000'),
  'Status': 'Lapped',
  'Points': 0.0,
  'Laps': 64.0},
 {'DriverNumber': '77',
  'BroadcastName': 'V BOTTAS',
  'Abbreviation': 'BOT',
  'DriverId': 'bottas',
  'TeamName': 'Cadillac',
  'TeamColor': '909090',
  'TeamId': 'cadillac',
  'FirstName': 'Valtteri',
  'LastName': 'Bottas',
  'FullName': 'Valtteri Bottas',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/V/VALBOT01_Valtteri_Bottas/valbot01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 16.0,
  'ClassifiedPosition': '16',
  'GridPosition': 21.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': Timedelta('0 days 00:00:53.390000'),
  'Status': 'Lapped',
  'Points': 0.0,
  'Laps': 64.0},
 {'DriverNumber': '11',
  'BroadcastName': 'S PEREZ',
  'Abbreviation': 'PER',
  'DriverId': 'perez',
  'TeamName': 'Cadillac',
  'TeamColor': '909090',
  'TeamId': 'cadillac',
  'FirstName': 'Sergio',
  'LastName': 'Perez',
  'FullName': 'Sergio Perez',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 17.0,
  'ClassifiedPosition': 'R',
  'GridPosition': 20.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': NaT,
  'Status': 'Retired',
  'Points': 0.0,
  'Laps': 39.0},
 {'DriverNumber': '1',
  'BroadcastName': 'L NORRIS',
  'Abbreviation': 'NOR',
  'DriverId': 'norris',
  'TeamName': 'McLaren',
  'TeamColor': 'F47600',
  'TeamId': 'mclaren',
  'FirstName': 'Lando',
  'LastName': 'Norris',
  'FullName': 'Lando Norris',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 18.0,
  'ClassifiedPosition': 'R',
  'GridPosition': 3.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': NaT,
  'Status': 'Retired',
  'Points': 0.0,
  'Laps': 38.0},
 {'DriverNumber': '63',
  'BroadcastName': 'G RUSSELL',
  'Abbreviation': 'RUS',
  'DriverId': 'russell',
  'TeamName': 'Mercedes',
  'TeamColor': '00D7B6',
  'TeamId': 'mercedes',
  'FirstName': 'George',
  'LastName': 'Russell',
  'FullName': 'George Russell',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GEORUS01_George_Russell/georus01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 19.0,
  'ClassifiedPosition': 'R',
  'GridPosition': 1.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': NaT,
  'Status': 'Retired',
  'Points': 0.0,
  'Laps': 29.0},
 {'DriverNumber': '14',
  'BroadcastName': 'F ALONSO',
  'Abbreviation': 'ALO',
  'DriverId': 'alonso',
  'TeamName': 'Aston Martin',
  'TeamColor': '229971',
  'TeamId': 'aston_martin',
  'FirstName': 'Fernando',
  'LastName': 'Alonso',
  'FullName': 'Fernando Alonso',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 20.0,
  'ClassifiedPosition': 'R',
  'GridPosition': 19.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': NaT,
  'Status': 'Retired',
  'Points': 0.0,
  'Laps': 23.0},
 {'DriverNumber': '23',
  'BroadcastName': 'A ALBON',
  'Abbreviation': 'ALB',
  'DriverId': 'albon',
  'TeamName': 'Williams',
  'TeamColor': '1868DB',
  'TeamId': 'williams',
  'FirstName': 'Alexander',
  'LastName': 'Albon',
  'FullName': 'Alexander Albon',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/A/ALEALB01_Alexander_Albon/alealb01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 21.0,
  'ClassifiedPosition': 'R',
  'GridPosition': 18.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': NaT,
  'Status': 'Retired',
  'Points': 0.0,
  'Laps': 11.0},
 {'DriverNumber': '41',
  'BroadcastName': 'A LINDBLAD',
  'Abbreviation': 'LIN',
  'DriverId': 'arvid_lindblad',
  'TeamName': 'Racing Bulls',
  'TeamColor': '6C98FF',
  'TeamId': 'rb',
  'FirstName': 'Arvid',
  'LastName': 'Lindblad',
  'FullName': 'Arvid Lindblad',
  'HeadshotUrl': 'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/A/ARVLIN01_Arvid_Lindblad/arvlin01.png.transform/1col/image.png',
  'CountryCode': '',
  'Position': 22.0,
  'ClassifiedPosition': 'W',
  'GridPosition': 9.0,
  'Q1': NaT,
  'Q2': NaT,
  'Q3': NaT,
  'Time': NaT,
  'Status': 'Did not start',
  'Points': 0.0,
  'Laps': 0.0}]

In [119]:
def parse_result(res, session_id):
    output = {}
    output['session_id'] = session_id
    output['driver_number'] = res['DriverNumber']
    output['broadcast_name'] = res['BroadcastName']
    output['abbreviation'] = res['Abbreviation']
    output['driver_id'] = res['DriverId']
    output['team_name'] = res['TeamName']
    output['team_color'] = '#' + res['TeamColor'].lower()
    output['team_id'] = res['TeamId']
    output['first_name'] = res['FirstName']
    output['last_name'] = res['LastName']
    output['full_name'] = res['FullName']
    output['headshot_url'] = res['HeadshotUrl']
    output['country_code'] = res['CountryCode']
    output['position'] = float(res['Position'])
    output['classified_position'] = str(res['ClassifiedPosition'])
    output['grid_position'] = float(res['GridPosition'])
    try:
        output['time_q1'] = float(res['Q1'].total_seconds())
    except TypeError:
        output['time_q1'] = None
    try:
        output['time_q2'] = float(res['Q2'].total_seconds())
    except TypeError:
        output['time_q1'] = None
    try:
        output['time_q3'] = float(res['Q3'].total_seconds())
    except TypeError:
        output['time_q1'] = None
    try:
        output['time_total'] = float(res['Time'].total_seconds())
    except TypeError:
        output['time_q1'] = None
    output['status'] = res['Status']
    output['points'] = float(res['Points'])
    output['laps'] = float(res['Laps'])
    return output

In [122]:
session = fastf1.get_session(2026, 1, 5)
session.load()
res = [parse_result(x, 'e') for x in session.results.to_dict(orient='records')]
columns = list(res[0].keys())
query = "insert into session_results ( {} ) values ( {} )".format(
    ",".join(columns),
    ",".join(["%s"] * len(columns))
)
with psycopg.connect(database_url) as conn:
    with conn.cursor() as cur:
        cur.executemany(query, [[r[c] for c in columns] for r in res])
        conn.commit()

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 81
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']

In [123]:
session = fastf1.get_session(2026, 6, 1)
session.load()

session.results['Q1'].value_counts()

core           INFO 	Loading data for Monaco Grand Prix - Practice 1 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']

Series([], Name: count, dtype: int64)

In [124]:
session.results.T

,1,3,5,6,10,11,12,14,16,18,...,30,31,41,43,44,55,63,77,81,87
DriverNumber,1,3,5,6,10,11,12,14,16,18,...,30,31,41,43,44,55,63,77,81,87
BroadcastName,L NORRIS,M VERSTAPPEN,G BORTOLETO,I HADJAR,P GASLY,S PEREZ,K ANTONELLI,F ALONSO,C LECLERC,L STROLL,...,L LAWSON,E OCON,A LINDBLAD,F COLAPINTO,L HAMILTON,C SAINZ,G RUSSELL,V BOTTAS,O PIASTRI,O BEARMAN
Abbreviation,NOR,VER,BOR,HAD,GAS,PER,ANT,ALO,LEC,STR,...,LAW,OCO,LIN,COL,HAM,SAI,RUS,BOT,PIA,BEA
DriverId,norris,max_verstappen,bortoleto,hadjar,gasly,perez,antonelli,alonso,leclerc,stroll,...,lawson,ocon,arvid_lindblad,colapinto,hamilton,sainz,russell,bottas,piastri,bearman
TeamName,McLaren,Red Bull Racing,Audi,Red Bull Racing,Alpine,Cadillac,Mercedes,Aston Martin,Ferrari,Aston Martin,...,Racing Bulls,Haas F1 Team,Racing Bulls,Alpine,Ferrari,Williams,Mercedes,Cadillac,McLaren,Haas F1 Team
TeamColor,F47600,4781D7,F50537,4781D7,00A1E8,909090,00D7B6,229971,ED1131,229971,...,6C98FF,9C9FA2,6C98FF,00A1E8,ED1131,1868DB,00D7B6,909090,F47600,9C9FA2
TeamId,mclaren,red_bull,audi,red_bull,alpine,cadillac,mercedes,aston_martin,ferrari,aston_martin,...,rb,haas,rb,alpine,ferrari,williams,mercedes,cadillac,mclaren,haas
FirstName,Lando,Max,Gabriel,Isack,Pierre,Sergio,Kimi,Fernando,Charles,Lance,...,Liam,Esteban,Arvid,Franco,Lewis,Carlos,George,Valtteri,Oscar,Oliver
LastName,Norris,Verstappen,Bortoleto,Hadjar,Gasly,Perez,Antonelli,Alonso,Leclerc,Stroll,...,Lawson,Ocon,Lindblad,Colapinto,Hamilton,Sainz,Russell,Bottas,Piastri,Bearman
FullName,Lando Norris,Max Verstappen,Gabriel Bortoleto,Isack Hadjar,Pierre Gasly,Sergio Perez,Kimi Antonelli,Fernando Alonso,Charles Leclerc,Lance Stroll,...,Liam Lawson,Esteban Ocon,Arvid Lindblad,Franco Colapinto,Lewis Hamilton,Carlos Sainz,George Russell,Valtteri Bottas,Oscar Piastri,Oliver Bearman
HeadshotUrl,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...
CountryCode,,,,,,,,,,,...,,,,,,,,,,
Position,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ClassifiedPosition,,,,,,,,,,,...,,,,,,,,,,
GridPosition,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q1,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
Q2,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
Q3,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
Time,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,...,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
Status,,,,,,,,,,,...,,,,,,,,,,
Points,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Laps,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
session.session_info

{'Meeting': {'Key': 1286,
  'Name': 'Monaco Grand Prix',
  'OfficialName': 'FORMULA 1 LOUIS VUITTON GRAND PRIX DE MONACO 2026',
  'Location': 'Monte Carlo',
  'Number': 6,
  'Country': {'Key': 114, 'Code': 'MON', 'Name': 'Monaco'},
  'Circuit': {'Key': 22, 'ShortName': 'Monte Carlo'}},
 'SessionStatus': 'Inactive',
 'ArchiveStatus': {'Status': 'Generating'},
 'Key': 11292,
 'Type': 'Practice',
 'Number': 1,
 'Name': 'Practice 1',
 'StartDate': datetime.datetime(2026, 6, 5, 13, 30),
 'EndDate': datetime.datetime(2026, 6, 5, 14, 30),
 'GmtOffset': datetime.timedelta(seconds=7200),
 'Path': '2026/2026-06-07_Monaco_Grand_Prix/2026-06-05_Practice_1/'}

In [23]:
session.session_start_time

datetime.timedelta(seconds=839, microseconds=938000)

In [5]:
session.laps.get_weather_data().nunique()

Time             58
AirTemp          14
Humidity         24
Pressure          4
Rainfall          2
TrackTemp        25
WindDirection    29
WindSpeed        14
dtype: int64

In [6]:
session.laps.get_weather_data().groupby('Time').describe()

                       AirTemp                                              \
                         count  mean           std   min   25%   50%   75%
Time
0 days 00:14:12.379000     2.0  23.1  0.000000e+00  23.1  23.1  23.1  23.1
0 days 00:15:12.400000    10.0  23.1  0.000000e+00  23.1  23.1  23.1  23.1
0 days 00:16:12.392000    15.0  23.6  7.354816e-15  23.6  23.6  23.6  23.6
0 days 00:17:12.402000    12.0  23.1  3.710688e-15  23.1  23.1  23.1  23.1
0 days 00:18:12.412000    14.0  23.6  3.686825e-15  23.6  23.6  23.6  23.6
0 days 00:19:12.402000    17.0  23.8  0.000000e+00  23.8  23.8  23.8  23.8
0 days 00:20:12.404000    17.0  23.6  0.000000e+00  23.6  23.6  23.6  23.6
0 days 00:21:12.403000    13.0  24.2  3.697782e-15  24.2  24.2  24.2  24.2
0 days 00:22:12.401000    14.0  23.7  3.686825e-15  23.7  23.7  23.7  23.7
0 days 00:23:12.415000    11.0  24.5  0.000000e+00  24.5  24.5  24.5  24.5
0 days 00:24:12.421000    14.0  23.8  3.686825e-15  23.8  23.8  23.8  23.8
0 days 00:25:12.426000    14.0  24.0  0.000000e+00  24.0  24.0  24.0  24.0
0 days 00:26:12.441000    11.0  24.4  0.000000e+00  24.4  24.4  24.4  24.4
0 days 00:27:12.449000    13.0  24.4  3.697782e-15  24.4  24.4  24.4  24.4
0 days 00:28:12.468000    14.0  24.0  0.000000e+00  24.0  24.0  24.0  24.0
0 days 00:29:12.495000    13.0  23.7  3.697782e-15  23.7  23.7  23.7  23.7
0 days 00:30:12.495000    12.0  23.8  0.000000e+00  23.8  23.8  23.8  23.8
0 days 00:31:12.508000    12.0  24.0  0.000000e+00  24.0  24.0  24.0  24.0
0 days 00:32:12.520000    13.0  23.8  3.697782e-15  23.8  23.8  23.8  23.8
0 days 00:33:12.534000    13.0  23.9  3.697782e-15  23.9  23.9  23.9  23.9
0 days 00:34:12.532000     9.0  23.6  0.000000e+00  23.6  23.6  23.6  23.6
0 days 00:35:12.573000    13.0  23.9  3.697782e-15  23.9  23.9  23.9  23.9
0 days 00:36:12.561000    13.0  24.0  0.000000e+00  24.0  24.0  24.0  24.0
0 days 00:37:12.569000     8.0  24.5  0.000000e+00  24.5  24.5  24.5  24.5
0 days 00:38:12.574000    12.0  24.6  3.710688e-15  24.6  24.6  24.6  24.6
0 days 00:39:12.570000    12.0  24.3  0.000000e+00  24.3  24.3  24.3  24.3
0 days 00:40:12.566000     9.0  23.8  0.000000e+00  23.8  23.8  23.8  23.8
0 days 00:41:12.589000     9.0  23.9  0.000000e+00  23.9  23.9  23.9  23.9
0 days 00:42:12.575000     9.0  24.0  0.000000e+00  24.0  24.0  24.0  24.0
0 days 00:43:12.576000     3.0  24.8  0.000000e+00  24.8  24.8  24.8  24.8
0 days 00:44:12.567000     7.0  24.6  3.837369e-15  24.6  24.6  24.6  24.6
0 days 00:45:12.580000     4.0  24.1  0.000000e+00  24.1  24.1  24.1  24.1
0 days 00:46:12.576000     7.0  24.0  0.000000e+00  24.0  24.0  24.0  24.0
0 days 00:47:12.577000     8.0  23.5  0.000000e+00  23.5  23.5  23.5  23.5
0 days 00:48:12.579000     6.0  23.7  0.000000e+00  23.7  23.7  23.7  23.7
0 days 00:49:12.583000     5.0  23.8  0.000000e+00  23.8  23.8  23.8  23.8
0 days 00:50:12.579000     1.0  23.8           NaN  23.8  23.8  23.8  23.8
0 days 00:57:12.584000     3.0  23.5  0.000000e+00  23.5  23.5  23.5  23.5
0 days 00:58:12.589000     8.0  23.9  0.000000e+00  23.9  23.9  23.9  23.9
0 days 00:59:12.585000    13.0  23.7  3.697782e-15  23.7  23.7  23.7  23.7
0 days 01:00:12.586000    12.0  23.7  0.000000e+00  23.7  23.7  23.7  23.7
0 days 01:01:12.570000    13.0  23.9  3.697782e-15  23.9  23.9  23.9  23.9
0 days 01:02:12.592000    17.0  23.8  0.000000e+00  23.8  23.8  23.8  23.8
0 days 01:03:12.587000    10.0  24.0  0.000000e+00  24.0  24.0  24.0  24.0
0 days 01:04:12.574000    16.0  24.0  0.000000e+00  24.0  24.0  24.0  24.0
0 days 01:05:12.598000    13.0  23.9  3.697782e-15  23.9  23.9  23.9  23.9
0 days 01:06:12.592000    15.0  24.2  3.677408e-15  24.2  24.2  24.2  24.2
0 days 01:07:12.587000    13.0  24.5  0.000000e+00  24.5  24.5  24.5  24.5
0 days 01:08:12.606000    13.0  24.6  3.697782e-15  24.6  24.6  24.6  24.6
0 days 01:09:12.593000    14.0  24.5  0.000000e+00  24.5  24.5  24.5  24.5
0 days 01:10:12.596000    15.0  24.3  3.677408e-15  24.3  24.3  24.3  24.3
0 days 01:11:12.591000     2.0  24.3  0.000000e+00  24.3  24.3  24.3  24.3
0 days 01:13:12.588000     1.0  24.2           NaN  24.2  24.2  24.2  24.2
0 days 01:14:12.598000    17.0  23.9  0.000000e+00  23.9  23.9  23.9  23.9
0 days 01:15:12.592000     7.0  24.0  0.000000e+00  24.0  24.0  24.0  24.0
0 days 01:16:12.586000    11.0  23.9  0.000000e+00  23.9  23.9  23.9  23.9
0 days 01:17:12.592000     5.0  23.9  0.000000e+00  23.9  23.9  23.9  23.9
0 days 01:18:12.594000    13.0  23.7  3.697782e-15  23.7  23.7  23.7  23.7

                             Humidity        ... WindDirection         \
                         max    count  mean  ...           75%    max
Time                                         ...
0 days 00:14:12.379000  23.1      2.0  63.3  ...         128.0  128.0
0 days 00:15:12.400000  23.1     10.0  63.3  ...         128.0  128.0
0 days 00:16:12.392000  23.6     15.0  63.5  ...           0.0    0.0
0 days 00:17:12.402000  23.1     12.0  64.3  ...         123.0  123.0
0 days 00:18:12.412000  23.6     14.0  64.3  ...         123.0  123.0
0 days 00:19:12.402000  23.8     17.0  64.3  ...         123.0  123.0
0 days 00:20:12.404000  23.6     17.0  64.3  ...         123.0  123.0
0 days 00:21:12.403000  24.2     13.0  64.3  ...         123.0  123.0
0 days 00:22:12.401000  23.7     14.0  61.7  ...         171.0  171.0
0 days 00:23:12.415000  24.5     11.0  61.7  ...         171.0  171.0
0 days 00:24:12.421000  23.8     14.0  61.7  ...         171.0  171.0
0 days 00:25:12.426000  24.0     14.0  61.7  ...         171.0  171.0
0 days 00:26:12.441000  24.4     11.0  60.3  ...         189.0  189.0
0 days 00:27:12.449000  24.4     13.0  59.8  ...         174.0  174.0
0 days 00:28:12.468000  24.0     14.0  60.0  ...         183.0  183.0
0 days 00:29:12.495000  23.7     13.0  60.0  ...         183.0  183.0
0 days 00:30:12.495000  23.8     12.0  61.2  ...         182.0  182.0
0 days 00:31:12.508000  24.0     12.0  61.2  ...         182.0  182.0
0 days 00:32:12.520000  23.8     13.0  61.2  ...         182.0  182.0
0 days 00:33:12.534000  23.9     13.0  60.8  ...         165.0  165.0
0 days 00:34:12.532000  23.6      9.0  60.8  ...         165.0  165.0
0 days 00:35:12.573000  23.9     13.0  60.7  ...         192.0  192.0
0 days 00:36:12.561000  24.0     13.0  60.7  ...         192.0  192.0
0 days 00:37:12.569000  24.5      8.0  60.7  ...         192.0  192.0
0 days 00:38:12.574000  24.6     12.0  60.7  ...         192.0  192.0
0 days 00:39:12.570000  24.3     12.0  61.3  ...         179.0  179.0
0 days 00:40:12.566000  23.8      9.0  61.3  ...         179.0  179.0
0 days 00:41:12.589000  23.9      9.0  61.3  ...         179.0  179.0
0 days 00:42:12.575000  24.0      9.0  61.3  ...         179.0  179.0
0 days 00:43:12.576000  24.8      3.0  61.3  ...         179.0  179.0
0 days 00:44:12.567000  24.6      7.0  61.3  ...         179.0  179.0
0 days 00:45:12.580000  24.1      4.0  61.1  ...         166.0  166.0
0 days 00:46:12.576000  24.0      7.0  60.8  ...         177.0  177.0
0 days 00:47:12.577000  23.5      8.0  60.8  ...         177.0  177.0
0 days 00:48:12.579000  23.7      6.0  61.0  ...         233.0  233.0
0 days 00:49:12.583000  23.8      5.0  60.0  ...          14.0   14.0
0 days 00:50:12.579000  23.8      1.0  59.5  ...         198.0  198.0
0 days 00:57:12.584000  23.5      3.0  60.2  ...         346.0  346.0
0 days 00:58:12.589000  23.9      8.0  60.2  ...         346.0  346.0
0 days 00:59:12.585000  23.7     13.0  60.2  ...         346.0  346.0
0 days 01:00:12.586000  23.7     12.0  63.3  ...         200.0  200.0
0 days 01:01:12.570000  23.9     13.0  63.3  ...         200.0  200.0
0 days 01:02:12.592000  23.8     17.0  64.3  ...         172.0  172.0
0 days 01:03:12.587000  24.0     10.0  63.1  ...         195.0  195.0
0 days 01:04:12.574000  24.0     16.0  63.1  ...         195.0  195.0
0 days 01:05:12.598000  23.9     13.0  61.9  ...         190.0  190.0
0 days 01:06:12.592000  24.2     15.0  62.1  ...         176.0  176.0
0 days 01:07:12.587000  24.5     13.0  61.4  ...         211.0  211.0
0 days 01:08:12.606000  24.6     13.0  60.5  ...         181.0  181.0
0 days 01:09:12.593000  24.5     14.0  60.4  ...         177.0  177.0
0 days 01:10:12.596000  24.3     15.0  60.4  ...         177.0  177.0
0 days 01:11:12.591000  24.3      2.0  61.0  ...         185.0  185.0
0 days 01:13:12.588000  24.2      1.0  60.9  ...         355.0  355.0
0 days 01:14:12.598000  23.9     17.0  60.9  ...         355.0  355.0
0 days 01:15:12.592000  24.0      7.0  62.1  ...         259.0  259.0
0 days 01:16:12.586000  23.9     11.0  62.8  ...         158.0  158.0
0 days 01:17:12.592000  23.9      5.0  63.0  ...         216.0  216.0
0 days 01:18:12.594000  23.7     13.0  63.0  ...         216.0  216.0

                       WindSpeed
                           count mean           std  min  25%  50%  75%  max
Time
0 days 00:14:12.379000       2.0  0.4  0.000000e+00  0.4  0.4  0.4  0.4  0.4
0 days 00:15:12.400000      10.0  0.4  0.000000e+00  0.4  0.4  0.4  0.4  0.4
0 days 00:16:12.392000      15.0  0.0  0.000000e+00  0.0  0.0  0.0  0.0  0.0
0 days 00:17:12.402000      12.0  0.4  5.797951e-17  0.4  0.4  0.4  0.4  0.4
0 days 00:18:12.412000      14.0  0.4  5.760664e-17  0.4  0.4  0.4  0.4  0.4
0 days 00:19:12.402000      17.0  0.4  0.000000e+00  0.4  0.4  0.4  0.4  0.4
0 days 00:20:12.404000      17.0  0.4  0.000000e+00  0.4  0.4  0.4  0.4  0.4
0 days 00:21:12.403000      13.0  0.4  5.777784e-17  0.4  0.4  0.4  0.4  0.4
0 days 00:22:12.401000      14.0  0.9  1.152133e-16  0.9  0.9  0.9  0.9  0.9
0 days 00:23:12.415000      11.0  0.9  0.000000e+00  0.9  0.9  0.9  0.9  0.9
0 days 00:24:12.421000      14.0  0.9  1.152133e-16  0.9  0.9  0.9  0.9  0.9
0 days 00:25:12.426000      14.0  0.9  1.152133e-16  0.9  0.9  0.9  0.9  0.9
0 days 00:26:12.441000      11.0  1.6  0.000000e+00  1.6  1.6  1.6  1.6  1.6
0 days 00:27:12.449000      13.0  0.8  1.155557e-16  0.8  0.8  0.8  0.8  0.8
0 days 00:28:12.468000      14.0  0.9  1.152133e-16  0.9  0.9  0.9  0.9  0.9
0 days 00:29:12.495000      13.0  0.9  1.155557e-16  0.9  0.9  0.9  0.9  0.9
0 days 00:30:12.495000      12.0  1.1  2.319180e-16  1.1  1.1  1.1  1.1  1.1
0 days 00:31:12.508000      12.0  1.1  2.319180e-16  1.1  1.1  1.1  1.1  1.1
0 days 00:32:12.520000      13.0  1.1  2.311114e-16  1.1  1.1  1.1  1.1  1.1
0 days 00:33:12.534000      13.0  0.7  0.000000e+00  0.7  0.7  0.7  0.7  0.7
0 days 00:34:12.532000       9.0  0.7  0.000000e+00  0.7  0.7  0.7  0.7  0.7
0 days 00:35:12.573000      13.0  0.9  1.155557e-16  0.9  0.9  0.9  0.9  0.9
0 days 00:36:12.561000      13.0  0.9  1.155557e-16  0.9  0.9  0.9  0.9  0.9
0 days 00:37:12.569000       8.0  0.9  0.000000e+00  0.9  0.9  0.9  0.9  0.9
0 days 00:38:12.574000      12.0  0.9  0.000000e+00  0.9  0.9  0.9  0.9  0.9
0 days 00:39:12.570000      12.0  0.5  0.000000e+00  0.5  0.5  0.5  0.5  0.5
0 days 00:40:12.566000       9.0  0.5  0.000000e+00  0.5  0.5  0.5  0.5  0.5
0 days 00:41:12.589000       9.0  0.5  0.000000e+00  0.5  0.5  0.5  0.5  0.5
0 days 00:42:12.575000       9.0  0.5  0.000000e+00  0.5  0.5  0.5  0.5  0.5
0 days 00:43:12.576000       3.0  0.5  0.000000e+00  0.5  0.5  0.5  0.5  0.5
0 days 00:44:12.567000       7.0  0.5  0.000000e+00  0.5  0.5  0.5  0.5  0.5
0 days 00:45:12.580000       4.0  0.5  0.000000e+00  0.5  0.5  0.5  0.5  0.5
0 days 00:46:12.576000       7.0  0.5  0.000000e+00  0.5  0.5  0.5  0.5  0.5
0 days 00:47:12.577000       8.0  0.5  0.000000e+00  0.5  0.5  0.5  0.5  0.5
0 days 00:48:12.579000       6.0  1.1  2.432377e-16  1.1  1.1  1.1  1.1  1.1
0 days 00:49:12.583000       5.0  0.4  0.000000e+00  0.4  0.4  0.4  0.4  0.4
0 days 00:50:12.579000       1.0  0.9           NaN  0.9  0.9  0.9  0.9  0.9
0 days 00:57:12.584000       3.0  0.6  0.000000e+00  0.6  0.6  0.6  0.6  0.6
0 days 00:58:12.589000       8.0  0.6  0.000000e+00  0.6  0.6  0.6  0.6  0.6
0 days 00:59:12.585000      13.0  0.6  1.155557e-16  0.6  0.6  0.6  0.6  0.6
0 days 01:00:12.586000      12.0  1.9  4.638361e-16  1.9  1.9  1.9  1.9  1.9
0 days 01:01:12.570000      13.0  1.9  4.622227e-16  1.9  1.9  1.9  1.9  1.9
0 days 01:02:12.592000      17.0  1.8  0.000000e+00  1.8  1.8  1.8  1.8  1.8
0 days 01:03:12.587000      10.0  1.7  0.000000e+00  1.7  1.7  1.7  1.7  1.7
0 days 01:04:12.574000      16.0  1.7  0.000000e+00  1.7  1.7  1.7  1.7  1.7
0 days 01:05:12.598000      13.0  1.4  0.000000e+00  1.4  1.4  1.4  1.4  1.4
0 days 01:06:12.592000      15.0  1.2  2.298380e-16  1.2  1.2  1.2  1.2  1.2
0 days 01:07:12.587000      13.0  1.1  2.311114e-16  1.1  1.1  1.1  1.1  1.1
0 days 01:08:12.606000      13.0  0.8  1.155557e-16  0.8  0.8  0.8  0.8  0.8
0 days 01:09:12.593000      14.0  0.9  1.152133e-16  0.9  0.9  0.9  0.9  0.9
0 days 01:10:12.596000      15.0  0.9  1.149190e-16  0.9  0.9  0.9  0.9  0.9
0 days 01:11:12.591000       2.0  1.1  0.000000e+00  1.1  1.1  1.1  1.1  1.1
0 days 01:13:12.588000       1.0  0.6           NaN  0.6  0.6  0.6  0.6  0.6
0 days 01:14:12.598000      17.0  0.6  0.000000e+00  0.6  0.6  0.6  0.6  0.6
0 days 01:15:12.592000       7.0  0.6  0.000000e+00  0.6  0.6  0.6  0.6  0.6
0 days 01:16:12.586000      11.0  0.6  1.164412e-16  0.6  0.6  0.6  0.6  0.6
0 days 01:17:12.592000       5.0  1.4  0.000000e+00  1.4  1.4  1.4  1.4  1.4
0 days 01:18:12.594000      13.0  1.4  0.000000e+00  1.4  1.4  1.4  1.4  1.4

[58 rows x 48 columns]

In [7]:
session.weather_data.nunique()

Time             80
AirTemp          18
Humidity         33
Pressure          4
Rainfall          2
TrackTemp        32
WindDirection    40
WindSpeed        15
dtype: int64

In [8]:
help(session.laps)

Help on Laps in module fastf1.core object:

class Laps(fastf1.internals.pandas_base.BaseDataFrame)
 |  Laps(*args, session: fastf1.core.Session | None = None, **kwargs)
 |
 |  Object for accessing lap (timing) data of multiple laps.
 |
 |  Args:
 |      *args: passed through to :class:`pandas.DataFrame` super class
 |      session: instance of session class; required for
 |        full functionality
 |      **kwargs: passed through to :class:`pandas.DataFrame`
 |        super class
 |
 |  This class allows for easily picking specific laps from all laps in a
 |  session. It implements some additional functionality on top of the usual
 |  `pandas.DataFrame` functionality. Among others, the laps' associated
 |  telemetry data can be accessed.
 |
 |  If for example you want to get the fastest lap of Bottas you can narrow
 |  it down like this::
 |
 |      import fastf1
 |
 |      session = fastf1.get_session(2019, 'Bahrain', 'Q')
 |      session.load()
 |      best_bottas = session.laps.pick_drivers('BOT').pick_fastest()
 |
 |      print(best_bottas['LapTime'])
 |      # Timedelta('0 days 00:01:28.256000')
 |
 |  Slicing this class will return :class:`Laps` again for slices containing
 |  multiple rows. Single rows will be returned as :class:`Lap`.
 |
 |  Method resolution order:
 |      Laps
 |      fastf1.internals.pandas_base.BaseDataFrame
 |      pandas.core.frame.DataFrame
 |      pandas.core.generic.NDFrame
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      pandas.core.indexing.IndexingMixin
 |      pandas.core.arraylike.OpsMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, *args, session: fastf1.core.Session | None = None, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  get_car_data(self, **kwargs) -> fastf1.core.Telemetry
 |      Car data for all laps in `self`
 |
 |      Slices the car data in :attr:`Session.car_data` using this set of laps
 |      and returns the result.
 |
 |      The data returned by this method does not contain computed telemetry
 |      channels. The can be added by calling the appropriate `add_*()` method
 |      on the returned telemetry object..
 |
 |      .. note:: Car data can only be returned if `self` contains laps of
 |          one driver only.
 |
 |      Args:
 |          **kwargs: Keyword arguments are passed to
 |              :meth:`Telemetry.slice_by_lap`
 |
 |      Returns:
 |          instance of :class:`Telemetry`
 |
 |  get_pos_data(self, **kwargs) -> fastf1.core.Telemetry
 |      Pos data for all laps in `self`
 |
 |      Slices the position data in :attr:`Session.pos_data` using this set
 |      of laps and returns the result.
 |
 |      .. note:: Position data can only be returned if `self` contains laps
 |          of one driver only.
 |
 |      Args:
 |          **kwargs: Keyword arguments are passed to
 |              :meth:`Telemetry.slice_by_lap`
 |
 |      Returns:
 |          instance of :class:`Telemetry`
 |
 |  get_telemetry(
 |      self,
 |      *,
 |      frequency: Union[int, Literal['original'], NoneType] = None
 |  ) -> fastf1.core.Telemetry
 |      Telemetry data for all laps in `self`
 |
 |      Telemetry data is the result of merging the returned data from
 |      :meth:`get_car_data` and :meth:`get_pos_data`. This means that
 |      telemetry data at least partially contains interpolated values!
 |      Telemetry data additionally already has computed channels added
 |      (e.g. Distance).
 |
 |      This method is provided for convenience and compatibility reasons. But
 |      using it does usually not produce the most accurate possible result.
 |      It is recommended to use :meth:`get_car_data` or :meth:`get_pos_data`
 |      when possible. This is also faster if merging of car and position data
 |      is not necessary and if not all computed channels are needed.
 |
 |      Resampling during merging is done according to the frequency set by
 |      :attr:`~Telemetry.TELEMETRY_FREQUENCY`.
 |
 |      .. note:: Telemetry can only be returned if `self` contains laps of one
 |          driver only.
 |
 |      Args:
 |          frequency: Optional frequency to overwrite the default value set by
 |              :attr:`~Telemetry.TELEMETRY_FREQUENCY`.
 |              (Either string 'original' or integer for a frequency in Hz)
 |
 |      Returns:
 |          instance of :class:`Telemetry`
 |
 |  get_weather_data(self) -> pandas.core.frame.DataFrame
 |      Return weather data for each lap in self.
 |
 |      Weather data is updated once per minute. This means that there are
 |      usually one or two data points per lap. This function will always
 |      return only one data point per lap:
 |
 |         - The first value within the duration of a lap
 |
 |      or
 |
 |          - the last known value before the end of the lap if there are
 |            no values within the duration of a lap
 |
 |      .. note::
 |          The returned DataFrame will have one row for each lap in `self`.
 |          If `self` contains laps from multiple drivers, these may overlap
 |          and the returned DataFrame may contain duplicate rows with
 |          duplicate index values.
 |
 |      See :func:`fastf1.api.weather_data` for available data
 |      channels.
 |
 |      If you wish to have more control over the data, you can access the
 |      weather data directly in :attr:`Session.weather_data`.
 |
 |      Returns:
 |          pandas.DataFrame
 |
 |      .. doctest::
 |
 |          >>> session = fastf1.get_session(2019, 'Monza', 'Q')
 |          >>> session.load(telemetry=False)
 |          >>> weather_data = session.laps.get_weather_data()
 |          >>> print(weather_data)
 |                               Time AirTemp  ... WindDirection WindSpeed
 |          20 0 days 00:20:14.613000    22.5  ...           212       2.0
 |          21 0 days 00:21:15.001000    22.5  ...           207       2.7
 |          23 0 days 00:23:14.854000    22.7  ...           210       2.3
 |          24 0 days 00:24:14.430000    23.2  ...           207       3.2
 |          26 0 days 00:26:14.315000    23.6  ...           238       1.8
 |          ..                    ...     ...  ...           ...       ...
 |          36 0 days 00:36:14.426000    23.0  ...           192       0.9
 |          37 0 days 00:37:14.391000    23.3  ...           213       0.9
 |          28 0 days 00:28:14.324000    23.5  ...           183       1.3
 |          34 0 days 00:34:14.385000    23.0  ...           272       0.8
 |          35 0 days 00:35:14.460000    23.2  ...           339       1.1
 |          <BLANKLINE>
 |          [275 rows x 8 columns]
 |
 |      Joining weather data with lap timing data:
 |
 |      .. doctest::
 |
 |          >>> import pandas as pd  # needed additionally to fastf1
 |
 |          # prepare the data for joining
 |          >>> laps = session.laps
 |          >>> laps = laps.reset_index(drop=True)
 |          >>> weather_data = weather_data.reset_index(drop=True)
 |
 |          # exclude the 'Time' column from weather data when joining
 |          >>> joined = pd.concat([laps, weather_data.loc[:, ~(weather_data.columns == 'Time')]], axis=1)
 |          >>> print(joined)
 |                                Time Driver  ... WindDirection WindSpeed
 |          0   0 days 00:21:01.358000    LEC  ...           212       2.0
 |          1   0 days 00:22:21.775000    LEC  ...           207       2.7
 |          2   0 days 00:24:03.991000    LEC  ...           210       2.3
 |          3   0 days 00:25:24.117000    LEC  ...           207       3.2
 |          4   0 days 00:27:09.461000    LEC  ...           238       1.8
 |          ..                     ...    ...  ...           ...       ...
 |          270 0 days 00:36:38.150000    KUB  ...           192       0.9
 |          271 0 days 00:38:37.508000    KUB  ...           213       0.9
 |          272 0 days 00:33:27.227000    VER  ...           183       1.3
 |          273 0 days 00:35:05.865000    VER  ...           272       0.8
 |          274 0 days 00:36:47.787000    VER  ...           339       1.1
 |          <BLANKLINE>
 |          [275 rows x 38 columns]
 |
 |  iterlaps(self, require: collections.abc.Iterable | None = None) -> collections.abc.Iterable[tuple[int, 'Lap']]
 |      Iterator for iterating over all laps in self.
 |
 |      This method wraps :meth:`pandas.DataFrame.iterrows`.
 |      It additionally provides the `require` keyword argument.
 |
 |      Args:
 |          require: Require is a list of column/telemetry channel names. All
 |              names listed in `require` must exist in the data and have a
 |              non-null value (tested with :func:`pandas.is_null`). The
 |              iterator only yields laps for which this is true. If require is
 |              left empty, the iterator will yield all laps.
 |      Yields:
 |          (index, lap): label and an instance of :class:`Lap`
 |
 |  join(self, *args, **kwargs)
 |      Wraps :meth:`pandas.DataFrame.join` and adds metadata propagation.
 |
 |      When calling ``self.join`` metadata will be propagated from self to the
 |      joined dataframe.
 |
 |  merge(self, *args, **kwargs)
 |      Wraps :meth:`pandas.DataFrame.merge` and adds metadata propagation.
 |
 |      When calling ``self.merge`` metadata will be propagated from self to
 |      the merged dataframe.
 |
 |  pick_accurate(self) -> 'Laps'
 |      Return all laps which pass the accuracy validation check
 |      (lap['IsAccurate'] is True).
 |
 |      Returns:
 |          instance of :class:`Laps`
 |
 |  pick_box_laps(self, which: str = 'both') -> 'Laps'
 |      Return all laps which are either in-laps, out-laps, or both.
 |      Note: a lap could be an in-lap and an out-lap at the same time.
 |      In that case, it will get returned regardless of the 'which'
 |      parameter.
 |
 |      Args:
 |          which (str): one of 'in'/'out'/'both'
 |
 |              - which='in': only laps in which the driver entered
 |                the pit lane are returned
 |              - which='out': only laps in which the driver exited
 |                the pit lane are returned
 |              - which='both': both in-laps and out-laps are returned
 |
 |      Returns:
 |          instance of :class:`Laps`
 |
 |  pick_compounds(self, compounds: str | collections.abc.Iterable[str]) -> 'Laps'
 |      Return all laps in self which were done on some specific compounds.
 |      ::
 |
 |          soft_laps = session_laps.pick_compounds("SOFT")
 |          slick_laps = session_laps.pick_compounds(['SOFT', 'MEDIUM', "HARD])
 |
 |      Args:
 |          compounds: may be "SOFT", "MEDIUM", "HARD", "INTERMEDIATE", "WET",
 |              "UNKNOWN", or "TEST_UNKNOWN"
 |
 |      Returns:
 |          instance of :class:`Laps`
 |
 |  pick_driver(self, identifier: int | str) -> 'Laps'
 |      Return all laps of a specific driver in self based on the driver's
 |      three letters identifier or based on the driver number.
 |
 |      .. deprecated:: 3.1.0
 |          pick_driver is deprecated and will be removed in a future release.
 |          Use :func:`pick_drivers` instead.
 |
 |          perez_laps = session_laps.pick_drivers('PER')
 |          bottas_laps = session_laps.pick_drivers(77)
 |          kimi_laps = session_laps.pick_drivers('RAI')
 |
 |      Args:
 |          identifier (str or int): Driver abbreviation or number
 |
 |      Returns:
 |          instance of :class:`Laps`
 |
 |  pick_drivers(self, identifiers: int | str | collections.abc.Iterable[int | str]) -> 'Laps'
 |      Return all laps of the specified driver or drivers in self based
 |      on the drivers' three letters identifier or the driver number. ::
 |
 |          ver_laps = session_laps.pick_drivers("VER")
 |          some_drivers_laps = session_laps.pick_drivers([5, 'BOT', 7])
 |
 |      Args:
 |          identifiers: Multiple driver abbreviations or driver numbers
 |              (can be mixed)
 |
 |      Returns:
 |          instance of :class:`Laps`
 |
 |  pick_fastest(self, only_by_time: bool = False) -> Optional[ForwardRef('Lap')]
 |      Return the lap with the fastest lap time.
 |
 |      This method will by default return the quickest lap out of self, that
 |      is also marked as personal best lap of a driver.
 |
 |      If the quickest lap by lap time is not marked as personal best, this
 |      means that it was not counted. This can be the case for example, if
 |      the driver exceeded track limits and the lap time was deleted.
 |
 |      If no lap is marked as personal best lap or self contains no laps,
 |      ``None`` is returned instead.
 |
 |      The check for personal best lap can be disabled, so that any quickest
 |      lap will be returned.
 |
 |      Args:
 |          only_by_time (bool): Ignore whether any laps are marked as
 |              personal best laps and simply return the lap that has the
 |              lowest lap time.
 |
 |      Returns:
 |          instance of :class:`Lap` or ``None``
 |
 |  pick_lap(self, lap_number: int) -> 'Laps'
 |      Return all laps of a specific LapNumber in self based on LapNumber.
 |
 |      .. deprecated:: 3.1.0
 |          pick_lap is deprecated and will be removed in a
 |          future release. Use :func:`pick_laps` instead.
 |
 |          lap_1 = session_laps.pick_lap(1)
 |          lap_25 = session_laps.pick_lap(25)
 |
 |      Args:
 |          lap_number (int): Lap number
 |
 |      Returns:
 |          instance of :class:`Laps`
 |
 |  pick_laps(self, lap_numbers: int | collections.abc.Iterable[int]) -> 'Laps'
 |      Return all laps of a specific LapNumber or a list of LapNumbers
 |      in self. ::
 |
 |          lap_1 = session_laps.pick_laps(1)
 |          lap_10_to_20 = session_laps.pick_lap(range(10, 21))
 |
 |      Args:
 |          lap_numbers: int for matching a single lap,
 |              an iterable of ints for matching multiple laps
 |
 |      Returns:
 |          instance of :class:`Laps`
 |
 |  pick_not_deleted(self) -> 'Laps'
 |      Return all laps whose lap times are NOT deleted.
 |
 |      Returns:
 |          instance of :class:`Laps`
 |
 |  pick_quicklaps(self, threshold: float | None = None) -> 'Laps'
 |      Return all laps with `LapTime` faster than a certain limit. By
 |      default, the threshold is 107% of the best `LapTime` of all laps
 |      in self.
 |
 |      Args:
 |          threshold: custom threshold coefficient
 |              (e.g. 1.05 for 105%)
 |
 |      Returns:
 |          instance of :class:`Laps`
 |
 |  pick_team(self, name: str) -> 'Laps'
 |      Return all laps of a specific team in self based on the
 |      team's name.
 |
 |      .. deprecated:: 3.1.0
 |          pick_team is deprecated and will be removed in a future release.
 |          Use :func:`pick_teams` instead.
 |
 |          mercedes = session_laps.pick_team('Mercedes')
 |          alfa_romeo = session_laps.pick_team('Alfa Romeo')
 |
 |      Args:
 |          name (str): Team name
 |
 |      Returns:
 |          instance of :class:`Laps`
 |
 |  pick_teams(self, names: str | collections.abc.Iterable[str]) -> 'Laps'
 |      Return all laps of the specified team or teams in self based
 |      on the team names. ::
 |
 |          rbr_laps = session_laps.pick_teams("Red Bull")
 |          some_drivers_laps = session_laps.pick_teams(['Haas', 'Alpine'])
 |
 |      Args:
 |          names: A single team name or team names
 |
 |      Returns:
 |          instance of :class:`Laps`
 |
 |  pick_track_status(self, status: str, how: str = 'equals') -> 'Laps'
 |      Return all laps set under a specific track status.
 |
 |      Args:
 |          status (str): The track status as a string, e.g. '1'
 |          how (str): one of 'equals'/'contains'/'excludes'/'any'/'none'
 |
 |              - how='equals': status='2' will only match '2'.
 |              - how='contains': status='2' will also match '267' and similar
 |              - how='excludes': status='26' will not match '267' but will
 |                match '27'
 |              - how='any': status='26' will match both '2' and '6'
 |              - how='none': status='26' will not match either '12' or '16'
 |
 |      Returns:
 |          instance of :class:`Laps`
 |
 |  pick_tyre(self, compound: str) -> 'Laps'
 |      Return all laps in self which were done on a specific compound.
 |
 |      .. deprecated:: 3.1.0
 |          pick_tyre is deprecated and will be removed in a future release.
 |          Use :func:`pick_compounds` instead.
 |
 |      Args:
 |          compound: may be "SOFT", "MEDIUM", "HARD",
 |              "INTERMEDIATE", "WET", "UNKNOWN", or "TEST_UNKNOWN"
 |
 |      Returns:
 |          instance of :class:`Laps`
 |
 |  pick_wo_box(self) -> 'Laps'
 |      Return all laps which are NOT in laps or out laps.
 |
 |      Returns:
 |          instance of :class:`Laps`
 |
 |  split_qualifying_sessions(self) -> list[typing.Optional[ForwardRef('Laps')]]
 |      Splits a lap object into individual laps objects for each
 |      qualifying session.
 |
 |      This method only works for qualifying sessions and requires that
 |      session status data is loaded.
 |
 |      Example::
 |
 |          q1, q2, q3 = laps.split_qualifying_sessions()
 |
 |      Returns: Three :class:`Laps` objects, one for Q1, Q2 and Q3
 |          each. If any of these sessions was cancelled, ``None`` will be
 |          returned instead of :class:`Laps`.
 |
 |  telemetry = <functools.cached_property object>
 |      Telemetry data for all laps in `self`
 |
 |      This is a cached (!) property for :meth:`get_telemetry`. It will
 |      return the same value as `get_telemetry` but cache the result so that
 |      the involved processing is only done once.
 |
 |      This is mainly provided for convenience and backwards compatibility.
 |
 |      See :meth:`get_telemetry` for more information.
 |
 |      .. note:: Telemetry can only be returned if `self` contains laps of
 |          one driver only.
 |
 |      Returns:
 |          instance of :class:`Telemetry`
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  QUICKLAP_THRESHOLD = 1.07
 |
 |  __annotations__ = {}
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from fastf1.internals.pandas_base.BaseDataFrame:
 |
 |  __repr__(self) -> str
 |      Return a string representation for a particular DataFrame.
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from fastf1.internals.pandas_base.BaseDataFrame:
 |
 |  base_class_view
 |      For a nicer debugging experience; can view DataFrame through
 |      this property in various IDEs
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from pandas.core.frame.DataFrame:
 |
 |  __arrow_c_stream__(self, requested_schema=None)
 |      Export the pandas DataFrame as an Arrow C stream PyCapsule.
 |
 |      This relies on pyarrow to convert the pandas DataFrame to the Arrow
 |      format (and follows the default behaviour of ``pyarrow.Table.from_pandas``
 |      in its handling of the index, i.e. store the index as a column except
 |      for RangeIndex).
 |      This conversion is not necessarily zero-copy.
 |
 |      Parameters
 |      ----------
 |      requested_schema : PyCapsule, default None
 |          The schema to which the dataframe should be casted, passed as a
 |          PyCapsule containing a C ArrowSchema representation of the
 |          requested schema.
 |
 |      Returns
 |      -------
 |      PyCapsule
 |
 |  __dataframe__(self, nan_as_null: 'bool' = False, allow_copy: 'bool' = True) -> 'DataFrameXchg'
 |      Return the dataframe interchange object implementing the interchange protocol.
 |
 |      Parameters
 |      ----------
 |      nan_as_null : bool, default False

In [137]:
session.race_control_messages["Time"].apply(type)

0      <class 'pandas._libs.tslibs.timestamps.Timesta...
1      <class 'pandas._libs.tslibs.timestamps.Timesta...
2      <class 'pandas._libs.tslibs.timestamps.Timesta...
3      <class 'pandas._libs.tslibs.timestamps.Timesta...
4      <class 'pandas._libs.tslibs.timestamps.Timesta...
                             ...
162    <class 'pandas._libs.tslibs.timestamps.Timesta...
163    <class 'pandas._libs.tslibs.timestamps.Timesta...
164    <class 'pandas._libs.tslibs.timestamps.Timesta...
165    <class 'pandas._libs.tslibs.timestamps.Timesta...
166    <class 'pandas._libs.tslibs.timestamps.Timesta...
Name: Time, Length: 167, dtype: object

In [130]:
session = fastf1.get_session(2026, 1, 5)
session.load()
session.race_control_messages.map(lambda x: str(type(x))).value_counts()

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 81
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']

Time                                                Category       Message        Status              Flag                Scope               Sector           RacingNumber        Lap
<class 'pandas._libs.tslibs.timestamps.Timestamp'>  <class 'str'>  <class 'str'>  <class 'NoneType'>  <class 'str'>       <class 'str'>       <class 'float'>  <class 'str'>       <class 'int'>    93
                                                                                                      <class 'NoneType'>  <class 'NoneType'>  <class 'float'>  <class 'NoneType'>  <class 'int'>    37
                                                                                                      <class 'str'>       <class 'str'>       <class 'float'>  <class 'NoneType'>  <class 'int'>    31
                                                                                  <class 'str'>       <class 'NoneType'>  <class 'NoneType'>  <class 'float'>  <class 'NoneType'>  <class 'int'>     6
Name: count, dtype: int64

In [134]:
df = session.race_control_messages
for col in df.columns:
    print(col)
    print(df[col].dropna().unique()[:5])
    print()

Time
<DatetimeArray>
['2026-03-08 03:08:08', '2026-03-08 03:20:00', '2026-03-08 03:21:22',
 '2026-03-08 03:21:25', '2026-03-08 03:21:26']
Length: 5, dtype: datetime64[ns]

Category
['Other' 'Flag' 'SafetyCar']

Message
['PINK HEAD PADDING MATERIAL MUST BE USED' 'GREEN LIGHT - PIT EXIT OPEN'
 'DOUBLE YELLOW IN TRACK SECTOR 6' 'CLEAR IN TRACK SECTOR 6'
 'YELLOW IN TRACK SECTOR 7']

Status
['DEPLOYED' 'ENDING']

Flag
['GREEN' 'DOUBLE YELLOW' 'CLEAR' 'YELLOW' 'BLUE']

Scope
['Track' 'Sector' 'Driver']

Sector
[ 6.  7. 20. 15. 13.]

RacingNumber
['77' '18' '11' '43' '14']

Lap
[0 1 6 7 8]

In [ ]:
def process_weather(row):
    output = {}
    output["time"] = float(row['Time'].total_seconds())
    output['air_temperature'] = float(row['AirTemp'])
    output['track_temperature'] = float(row['TrackTemp'])
    output['humidity'] = float(row['Humidity'])
    output['pressure'] = float(row['Pressure'])
    output['rainfall'] = float(row['rainfall'])
    output['wind_direction'] = float(row['WindDirection'])
    output['wind_speed'] = float(row['WindSpeed'])
    return output

In [141]:
session.laps.head().T

,0,1,2,3,4
Time,0 days 01:03:56.437000,0 days 01:05:23.781000,0 days 01:06:50.644000,0 days 01:08:16.501000,0 days 01:09:42.074000
Driver,NOR,NOR,NOR,NOR,NOR
DriverNumber,1,1,1,1,1
LapTime,0 days 00:01:36.458000,0 days 00:01:27.344000,0 days 00:01:26.863000,0 days 00:01:25.857000,0 days 00:01:25.573000
LapNumber,1.0,2.0,3.0,4.0,5.0
Stint,1.0,1.0,1.0,1.0,1.0
PitOutTime,NaT,NaT,NaT,NaT,NaT
PitInTime,NaT,NaT,NaT,NaT,NaT
Sector1Time,NaT,0 days 00:00:31.074000,0 days 00:00:30.541000,0 days 00:00:30.190000,0 days 00:00:29.930000
Sector2Time,0 days 00:00:18.163000,0 days 00:00:18.116000,0 days 00:00:18.252000,0 days 00:00:18.193000,0 days 00:00:17.868000
Sector3Time,0 days 00:00:38.796000,0 days 00:00:38.154000,0 days 00:00:38.070000,0 days 00:00:37.474000,0 days 00:00:37.775000
Sector1SessionTime,NaT,0 days 01:04:27.511000,0 days 01:05:54.322000,0 days 01:07:20.834000,0 days 01:08:46.431000
Sector2SessionTime,0 days 01:03:17.998000,0 days 01:04:45.627000,0 days 01:06:12.574000,0 days 01:07:39.027000,0 days 01:09:04.299000
Sector3SessionTime,0 days 01:03:56.692000,0 days 01:05:23.781000,0 days 01:06:50.644000,0 days 01:08:16.501000,0 days 01:09:42.074000
SpeedI1,229.0,243.0,245.0,249.0,260.0
SpeedI2,291.0,287.0,311.0,304.0,297.0
SpeedFL,304.0,303.0,286.0,283.0,280.0
SpeedST,217.0,260.0,273.0,276.0,276.0
IsPersonalBest,False,True,True,True,True
Compound,MEDIUM,MEDIUM,MEDIUM,MEDIUM,MEDIUM
TyreLife,1.0,2.0,3.0,4.0,5.0
FreshTyre,True,True,True,True,True
Team,McLaren,McLaren,McLaren,McLaren,McLaren
LapStartTime,0 days 01:02:19.743000,0 days 01:03:56.437000,0 days 01:05:23.781000,0 days 01:06:50.644000,0 days 01:08:16.501000
LapStartDate,2026-03-08 04:03:26.366000,2026-03-08 04:05:03.060000,2026-03-08 04:06:30.404000,2026-03-08 04:07:57.267000,2026-03-08 04:09:23.124000
TrackStatus,1,1,1,1,1
Position,6.0,6.0,7.0,7.0,7.0
Deleted,False,False,False,False,False
DeletedReason,,,,,
FastF1Generated,False,False,False,False,False
IsAccurate,False,True,True,True,True

In [143]:
df = session.laps
for col in df.columns:
    print(col)
    print(df[col].apply(type).value_counts())
    print(df[col].dropna().unique()[:5])
    print()

Time
Time
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>    1007
Name: count, dtype: int64
<TimedeltaArray>
['0 days 01:03:56.437000', '0 days 01:05:23.781000', '0 days 01:06:50.644000',
 '0 days 01:08:16.501000', '0 days 01:09:42.074000']
Length: 5, dtype: timedelta64[ns]

Driver
Driver
<class 'str'>    1007
Name: count, dtype: int64
['NOR' 'GAS' 'PER' 'ANT' 'ALO']

DriverNumber
DriverNumber
<class 'str'>    1007
Name: count, dtype: int64
['1' '10' '11' '12' '14']

LapTime
LapTime
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>    1000
<class 'pandas._libs.tslibs.nattype.NaTType'>            7
Name: count, dtype: int64
<TimedeltaArray>
['0 days 00:01:36.458000', '0 days 00:01:27.344000', '0 days 00:01:26.863000',
 '0 days 00:01:25.857000', '0 days 00:01:25.573000']
Length: 5, dtype: timedelta64[ns]

LapNumber
LapNumber
<class 'float'>    1007
Name: count, dtype: int64
[1. 2. 3. 4. 5.]

Stint
Stint
<class 'float'>    1007
Name: count, dtype: int64
[1. 2. 3. 4. 5.]

PitOutTime
PitOutTime
<class 'pandas._libs.tslibs.nattype.NaTType'>         975
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>     32
Name: count, dtype: int64
<TimedeltaArray>
['0 days 01:18:34.141000', '0 days 01:53:00.323000', '0 days 01:18:39.918000',
 '0 days 01:30:39.693000', '0 days 02:08:07.124000']
Length: 5, dtype: timedelta64[ns]

PitInTime
PitInTime
<class 'pandas._libs.tslibs.nattype.NaTType'>         974
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>     33
Name: count, dtype: int64
<TimedeltaArray>
['0 days 01:18:15.593000', '0 days 01:52:42.584000', '0 days 01:18:21.012000',
 '0 days 01:30:18.038000', '0 days 02:07:47.788000']
Length: 5, dtype: timedelta64[ns]

Sector1Time
Sector1Time
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>    984
<class 'pandas._libs.tslibs.nattype.NaTType'>          23
Name: count, dtype: int64
<TimedeltaArray>
['0 days 00:00:31.074000', '0 days 00:00:30.541000', '0 days 00:00:30.190000',
 '0 days 00:00:29.930000', '0 days 00:00:30.025000']
Length: 5, dtype: timedelta64[ns]

Sector2Time
Sector2Time
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>    1004
<class 'pandas._libs.tslibs.nattype.NaTType'>            3
Name: count, dtype: int64
<TimedeltaArray>
['0 days 00:00:18.163000', '0 days 00:00:18.116000', '0 days 00:00:18.252000',
 '0 days 00:00:18.193000', '0 days 00:00:17.868000']
Length: 5, dtype: timedelta64[ns]

Sector3Time
Sector3Time
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>    1001
<class 'pandas._libs.tslibs.nattype.NaTType'>            6
Name: count, dtype: int64
<TimedeltaArray>
['0 days 00:00:38.796000', '0 days 00:00:38.154000', '0 days 00:00:38.070000',
 '0 days 00:00:37.474000', '0 days 00:00:37.775000']
Length: 5, dtype: timedelta64[ns]

Sector1SessionTime
Sector1SessionTime
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>    980
<class 'pandas._libs.tslibs.nattype.NaTType'>          27
Name: count, dtype: int64
<TimedeltaArray>
['0 days 01:04:27.511000', '0 days 01:05:54.322000', '0 days 01:07:20.834000',
 '0 days 01:08:46.431000', '0 days 01:10:12.099000']
Length: 5, dtype: timedelta64[ns]

Sector2SessionTime
Sector2SessionTime
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>    1004
<class 'pandas._libs.tslibs.nattype.NaTType'>            3
Name: count, dtype: int64
<TimedeltaArray>
['0 days 01:03:17.998000', '0 days 01:04:45.627000', '0 days 01:06:12.574000',
 '0 days 01:07:39.027000', '0 days 01:09:04.299000']
Length: 5, dtype: timedelta64[ns]

Sector3SessionTime
Sector3SessionTime
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>    1001
<class 'pandas._libs.tslibs.nattype.NaTType'>            6
Name: count, dtype: int64
<TimedeltaArray>
['0 days 01:03:56.692000', '0 days 01:05:23.781000', '0 days 01:06:50.644000',
 '0 days 01:08:16.501000', '0 days 01:09:42.074000']
Length: 5, dtype: timedelta64[ns]

SpeedI1
SpeedI1
<class 'float'>    1007
Name: count, dtype: int64
[229. 243. 245. 249. 260.]

SpeedI2
SpeedI2
<class 'float'>    1007
Name: count, dtype: int64
[291. 287. 311. 304. 297.]

SpeedFL
SpeedFL
<class 'float'>    1007
Name: count, dtype: int64
[304. 303. 286. 283. 280.]

SpeedST
SpeedST
<class 'float'>    1007
Name: count, dtype: int64
[217. 260. 273. 276. 285.]

IsPersonalBest
IsPersonalBest
<class 'bool'>     1005
<class 'float'>       2
Name: count, dtype: int64
[False True]

Compound
Compound
<class 'str'>    1007
Name: count, dtype: int64
['MEDIUM' 'HARD' 'SOFT']

TyreLife
TyreLife
<class 'float'>    1007
Name: count, dtype: int64
[1. 2. 3. 4. 5.]

FreshTyre
FreshTyre
<class 'bool'>    1007
Name: count, dtype: int64
[ True False]

Team
Team
<class 'str'>    1007
Name: count, dtype: int64
['McLaren' 'Alpine' 'Cadillac' 'Mercedes' 'Aston Martin']

LapStartTime
LapStartTime
<class 'pandas._libs.tslibs.timedeltas.Timedelta'>    1007
Name: count, dtype: int64
<TimedeltaArray>
['0 days 01:02:19.743000', '0 days 01:03:56.437000', '0 days 01:05:23.781000',
 '0 days 01:06:50.644000', '0 days 01:08:16.501000']
Length: 5, dtype: timedelta64[ns]

LapStartDate
LapStartDate
<class 'pandas._libs.tslibs.timestamps.Timestamp'>    1005
<class 'pandas._libs.tslibs.nattype.NaTType'>            2
Name: count, dtype: int64
<DatetimeArray>
['2026-03-08 04:03:26.366000', '2026-03-08 04:05:03.060000',
 '2026-03-08 04:06:30.404000', '2026-03-08 04:07:57.267000',
 '2026-03-08 04:09:23.124000']
Length: 5, dtype: datetime64[ns]

TrackStatus
TrackStatus
<class 'str'>    1007
Name: count, dtype: int64
['1' '16' '6' '671' '126']

Position
Position
<class 'float'>    1007
Name: count, dtype: int64
[6. 7. 9. 5. 8.]

Deleted
Deleted
<class 'bool'>    1007
Name: count, dtype: int64
[False  True]

DeletedReason
DeletedReason
<class 'str'>      1005
<class 'float'>       2
Name: count, dtype: int64
['' 'TRACK LIMITS AT TURN 10 LAP 5 ' 'TRACK LIMITS AT TURN 3 LAP 16 '
 'TRACK LIMITS AT TURN 3 LAP 6 ' 'TRACK LIMITS AT TURN 3 LAP 53 ']

FastF1Generated
FastF1Generated
<class 'bool'>    1007
Name: count, dtype: int64
[False  True]

IsAccurate
IsAccurate
<class 'bool'>    1007
Name: count, dtype: int64
[False  True]

In [144]:
database_url = "postgresql://formula_one:formula_one@127.0.0.1:5434/formula_one"

In [145]:
session = fastf1.get_session(2026, 5, 5)
session.load()
df = session.laps

core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '44', '3', '16', '6', '43', '30', '10', '55', '87', '81', '27', '5', '31', '18', '77', '11', '1', '63', '14', '23', '41']

In [150]:
with psycopg.connect(database_url) as conn:
    with conn.cursor() as cur:
        cur.execute('select * from race_session  ; ')
        sessions = cur.fetchall()
sessions

[('Y2026R01S5',
  2026,
  1,
  5,
  False,
  'Australian Grand Prix',
  'Race',
  {'Meeting': {'Key': 1279,
    'Name': 'Australian Grand Prix',
    'OfficialName': 'FORMULA 1 QATAR AIRWAYS AUSTRALIAN GRAND PRIX 2026',
    'Location': 'Melbourne',
    'Number': 1,
    'Country': {'Key': 5, 'Code': 'AUS', 'Name': 'Australia'},
    'Circuit': {'Key': 10, 'ShortName': 'Melbourne'}},
   'SessionStatus': 'Inactive',
   'ArchiveStatus': {'Status': 'Generating'},
   'Key': 11234,
   'Type': 'Race',
   'Name': 'Race',
   'StartDate': '2026-03-08 15:00:00',
   'EndDate': '2026-03-08 17:00:00',
   'GmtOffset': '11:00:00',
   'Path': '2026/2026-03-08_Australian_Grand_Prix/2026-03-08_Race/'},
  {'RoundNumber': 1,
   'Country': 'Australia',
   'Location': 'Melbourne',
   'OfficialEventName': 'FORMULA 1 QATAR AIRWAYS AUSTRALIAN GRAND PRIX 2026',
   'EventDate': '2026-03-08 00:00:00',
   'EventName': 'Australian Grand Prix',
   'EventFormat': 'conventional',
   'Session1': 'Practice 1',
   'Session1Date': '2026-03-06 12:30:00+11:00',
   'Session1DateUtc': '2026-03-06 01:30:00',
   'Session2': 'Practice 2',
   'Session2Date': '2026-03-06 16:00:00+11:00',
   'Session2DateUtc': '2026-03-06 05:00:00',
   'Session3': 'Practice 3',
   'Session3Date': '2026-03-07 12:30:00+11:00',
   'Session3DateUtc': '2026-03-07 01:30:00',
   'Session4': 'Qualifying',
   'Session4Date': '2026-03-07 16:00:00+11:00',
   'Session4DateUtc': '2026-03-07 05:00:00',
   'Session5': 'Race',
   'Session5Date': '2026-03-08 15:00:00+11:00',
   'Session5DateUtc': '2026-03-08 04:00:00',
   'F1ApiSupport': True},
  3739.743,
  datetime.datetime(2026, 3, 8, 3, 1, 6, 623000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  58.0)]

In [158]:
with psycopg.connect(database_url) as conn:
    with conn.cursor() as cur:
        cur.execute('select * from session_weather  ; ')
        weather = cur.fetchall()
weather

[('Y2026R01S5',
  1,
  13.466,
  datetime.datetime(2026, 3, 8, 3, 1, 20, 89000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.1,
  36.2,
  55.8,
  1013.7,
  False,
  114.0,
  1.8),
 ('Y2026R01S5',
  2,
  73.482,
  datetime.datetime(2026, 3, 8, 3, 2, 20, 105000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.2,
  35.9,
  55.1,
  1013.6,
  False,
  110.0,
  3.0),
 ('Y2026R01S5',
  3,
  133.483,
  datetime.datetime(2026, 3, 8, 3, 3, 20, 106000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.2,
  35.6,
  55.2,
  1013.6,
  False,
  115.0,
  3.2),
 ('Y2026R01S5',
  4,
  193.485,
  datetime.datetime(2026, 3, 8, 3, 4, 20, 108000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.1,
  35.7,
  55.7,
  1013.7,
  False,
  104.0,
  3.4),
 ('Y2026R01S5',
  5,
  253.518,
  datetime.datetime(2026, 3, 8, 3, 5, 20, 141000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.1,
  35.8,
  55.8,
  1013.8,
  False,
  108.0,
  3.1),
 ('Y2026R01S5',
  6,
  313.531,
  datetime.datetime(2026, 3, 8, 3, 6, 20, 154000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.2,
  35.7,
  55.5,
  1013.7,
  False,
  109.0,
  3.4),
 ('Y2026R01S5',
  7,
  373.532,
  datetime.datetime(2026, 3, 8, 3, 7, 20, 155000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.2,
  35.5,
  55.7,
  1013.6,
  False,
  128.0,
  1.7),
 ('Y2026R01S5',
  8,
  433.522,
  datetime.datetime(2026, 3, 8, 3, 8, 20, 145000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.1,
  35.7,
  56.6,
  1013.7,
  False,
  106.0,
  2.1),
 ('Y2026R01S5',
  9,
  493.537,
  datetime.datetime(2026, 3, 8, 3, 9, 20, 160000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.1,
  35.4,
  57.0,
  1013.7,
  False,
  118.0,
  3.1),
 ('Y2026R01S5',
  10,
  553.538,
  datetime.datetime(2026, 3, 8, 3, 10, 20, 161000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.2,
  35.6,
  55.9,
  1013.5,
  False,
  154.0,
  2.4),
 ('Y2026R01S5',
  11,
  613.552,
  datetime.datetime(2026, 3, 8, 3, 11, 20, 175000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.1,
  36.0,
  56.6,
  1013.6,
  False,
  124.0,
  1.3),
 ('Y2026R01S5',
  12,
  673.569,
  datetime.datetime(2026, 3, 8, 3, 12, 20, 192000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.2,
  36.3,
  56.1,
  1013.6,
  False,
  98.0,
  1.6),
 ('Y2026R01S5',
  13,
  733.555,
  datetime.datetime(2026, 3, 8, 3, 13, 20, 178000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.1,
  36.7,
  56.1,
  1013.6,
  False,
  127.0,
  2.3),
 ('Y2026R01S5',
  14,
  793.569,
  datetime.datetime(2026, 3, 8, 3, 14, 20, 192000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.1,
  36.3,
  56.1,
  1013.5,
  False,
  109.0,
  3.2),
 ('Y2026R01S5',
  15,
  853.575,
  datetime.datetime(2026, 3, 8, 3, 15, 20, 198000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.1,
  36.3,
  56.1,
  1013.5,
  False,
  132.0,
  2.2),
 ('Y2026R01S5',
  16,
  913.555,
  datetime.datetime(2026, 3, 8, 3, 16, 20, 178000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.1,
  35.6,
  55.9,
  1013.5,
  False,
  131.0,
  3.8),
 ('Y2026R01S5',
  17,
  973.571,
  datetime.datetime(2026, 3, 8, 3, 17, 20, 194000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.1,
  35.6,
  56.0,
  1013.5,
  False,
  133.0,
  2.1),
 ('Y2026R01S5',
  18,
  1033.563,
  datetime.datetime(2026, 3, 8, 3, 18, 20, 186000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.1,
  35.6,
  56.3,
  1013.5,
  False,
  110.0,
  2.3),
 ('Y2026R01S5',
  19,
  1093.574,
  datetime.datetime(2026, 3, 8, 3, 19, 20, 197000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.1,
  35.7,
  56.5,
  1013.3,
  False,
  118.0,
  1.5),
 ('Y2026R01S5',
  20,
  1153.558,
  datetime.datetime(2026, 3, 8, 3, 20, 20, 181000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.2,
  35.6,
  56.0,
  1013.4,
  False,
  95.0,
  0.9),
 ('Y2026R01S5',
  21,
  1213.56,
  datetime.datetime(2026, 3, 8, 3, 21, 20, 183000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.2,
  35.5,
  56.4,
  1013.3,
  False,
  110.0,
  2.3),
 ('Y2026R01S5',
  22,
  1273.577,
  datetime.datetime(2026, 3, 8, 3, 22, 20, 200000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.2,
  35.5,
  56.5,
  1013.3,
  False,
  109.0,
  2.4),
 ('Y2026R01S5',
  23,
  1333.577,
  datetime.datetime(2026, 3, 8, 3, 23, 20, 200000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.3,
  35.8,
  56.0,
  1013.3,
  False,
  108.0,
  3.7),
 ('Y2026R01S5',
  24,
  1393.598,
  datetime.datetime(2026, 3, 8, 3, 24, 20, 221000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.3,
  34.9,
  55.1,
  1013.3,
  False,
  130.0,
  3.8),
 ('Y2026R01S5',
  25,
  1453.592,
  datetime.datetime(2026, 3, 8, 3, 25, 20, 215000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.2,
  34.9,
  55.6,
  1013.3,
  False,
  137.0,
  0.8),
 ('Y2026R01S5',
  26,
  1513.612,
  datetime.datetime(2026, 3, 8, 3, 26, 20, 235000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.2,
  34.7,
  55.8,
  1013.3,
  False,
  114.0,
  1.9),
 ('Y2026R01S5',
  27,
  1573.615,
  datetime.datetime(2026, 3, 8, 3, 27, 20, 238000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.3,
  33.3,
  56.4,
  1013.2,
  False,
  126.0,
  2.2),
 ('Y2026R01S5',
  28,
  1633.629,
  datetime.datetime(2026, 3, 8, 3, 28, 20, 252000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.4,
  34.6,
  55.7,
  1013.2,
  False,
  125.0,
  2.8),
 ('Y2026R01S5',
  29,
  1693.627,
  datetime.datetime(2026, 3, 8, 3, 29, 20, 250000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.5,
  33.4,
  55.1,
  1013.3,
  False,
  124.0,
  2.3),
 ('Y2026R01S5',
  30,
  1753.613,
  datetime.datetime(2026, 3, 8, 3, 30, 20, 236000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.5,
  34.3,
  55.6,
  1013.3,
  False,
  126.0,
  2.3),
 ('Y2026R01S5',
  31,
  1813.613,
  datetime.datetime(2026, 3, 8, 3, 31, 20, 236000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.4,
  33.5,
  55.8,
  1013.2,
  False,
  130.0,
  1.9),
 ('Y2026R01S5',
  32,
  1873.632,
  datetime.datetime(2026, 3, 8, 3, 32, 20, 255000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.4,
  35.3,
  55.5,
  1013.3,
  False,
  0.0,
  0.0),
 ('Y2026R01S5',
  33,
  1933.63,
  datetime.datetime(2026, 3, 8, 3, 33, 20, 253000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.4,
  35.9,
  55.6,
  1013.2,
  False,
  212.0,
  0.6),
 ('Y2026R01S5',
  34,
  1993.636,
  datetime.datetime(2026, 3, 8, 3, 34, 20, 259000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.4,
  35.5,
  55.5,
  1013.3,
  False,
  113.0,
  1.1),
 ('Y2026R01S5',
  35,
  2053.648,
  datetime.datetime(2026, 3, 8, 3, 35, 20, 271000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.4,
  35.5,
  55.5,
  1013.3,
  False,
  101.0,
  3.7),
 ('Y2026R01S5',
  36,
  2113.678,
  datetime.datetime(2026, 3, 8, 3, 36, 20, 301000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.4,
  35.5,
  55.0,
  1013.3,
  False,
  192.0,
  2.1),
 ('Y2026R01S5',
  37,
  2173.68,
  datetime.datetime(2026, 3, 8, 3, 37, 20, 303000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.4,
  35.8,
  56.0,
  1013.3,
  False,
  90.0,
  2.4),
 ('Y2026R01S5',
  38,
  2233.68,
  datetime.datetime(2026, 3, 8, 3, 38, 20, 303000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.4,
  35.8,
  56.0,
  1013.3,
  False,
  90.0,
  2.4),
 ('Y2026R01S5',
  39,
  2293.675,
  datetime.datetime(2026, 3, 8, 3, 39, 20, 298000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.4,
  35.3,
  55.2,
  1013.2,
  False,
  124.0,
  1.6),
 ('Y2026R01S5',
  40,
  2353.684,
  datetime.datetime(2026, 3, 8, 3, 40, 20, 307000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.4,
  35.6,
  55.8,
  1013.2,
  False,
  128.0,
  1.0),
 ('Y2026R01S5',
  41,
  2413.681,
  datetime.datetime(2026, 3, 8, 3, 41, 20, 304000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.4,
  35.2,
  55.9,
  1013.2,
  False,
  154.0,
  1.8),
 ('Y2026R01S5',
  42,
  2473.683,
  datetime.datetime(2026, 3, 8, 3, 42, 20, 306000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.4,
  35.4,
  55.2,
  1013.1,
  False,
  125.0,
  2.3),
 ('Y2026R01S5',
  43,
  2533.684,
  datetime.datetime(2026, 3, 8, 3, 43, 20, 307000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.4,
  35.2,
  55.4,
  1013.2,
  False,
  125.0,
  3.9),
 ('Y2026R01S5',
  44,
  2593.671,
  datetime.datetime(2026, 3, 8, 3, 44, 20, 294000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.5,
  35.0,
  55.1,
  1013.1,
  False,
  121.0,
  2.3),
 ('Y2026R01S5',
  45,
  2653.669,
  datetime.datetime(2026, 3, 8, 3, 45, 20, 292000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.5,
  35.9,
  55.7,
  1013.1,
  False,
  123.0,
  2.3),
 ('Y2026R01S5',
  46,
  2713.675,
  datetime.datetime(2026, 3, 8, 3, 46, 20, 298000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.7,
  37.1,
  55.5,
  1013.1,
  False,
  124.0,
  1.5),
 ('Y2026R01S5',
  47,
  2773.702,
  datetime.datetime(2026, 3, 8, 3, 47, 20, 325000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.7,
  37.6,
  54.5,
  1013.1,
  False,
  100.0,
  2.7),
 ('Y2026R01S5',
  48,
  2833.704,
  datetime.datetime(2026, 3, 8, 3, 48, 20, 327000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.8,
  39.1,
  54.3,
  1013.1,
  False,
  117.0,
  2.0),
 ('Y2026R01S5',
  49,
  2893.704,
  datetime.datetime(2026, 3, 8, 3, 49, 20, 327000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.9,
  39.1,
  54.3,
  1013.0,
  False,
  116.0,
  2.4),
 ('Y2026R01S5',
  50,
  2953.708,
  datetime.datetime(2026, 3, 8, 3, 50, 20, 331000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.9,
  38.9,
  54.3,
  1013.1,
  False,
  120.0,
  2.6),
 ('Y2026R01S5',
  51,
  3013.708,
  datetime.datetime(2026, 3, 8, 3, 51, 20, 331000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.9,
  38.0,
  55.1,
  1013.0,
  False,
  99.0,
  1.8),
 ('Y2026R01S5',
  52,
  3073.721,
  datetime.datetime(2026, 3, 8, 3, 52, 20, 344000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.9,
  37.8,
  54.9,
  1012.9,
  False,
  103.0,
  1.1),
 ('Y2026R01S5',
  53,
  3133.72,
  datetime.datetime(2026, 3, 8, 3, 53, 20, 343000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.0,
  37.2,
  55.1,
  1013.0,
  False,
  137.0,
  3.7),
 ('Y2026R01S5',
  54,
  3193.72,
  datetime.datetime(2026, 3, 8, 3, 54, 20, 343000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.0,
  37.0,
  54.0,
  1013.0,
  False,
  95.0,
  1.2),
 ('Y2026R01S5',
  55,
  3253.725,
  datetime.datetime(2026, 3, 8, 3, 55, 20, 348000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.0,
  36.8,
  54.2,
  1012.8,
  False,
  156.0,
  2.0),
 ('Y2026R01S5',
  56,
  3313.728,
  datetime.datetime(2026, 3, 8, 3, 56, 20, 351000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.9,
  37.3,
  54.5,
  1012.9,
  False,
  126.0,
  1.5),
 ('Y2026R01S5',
  57,
  3373.725,
  datetime.datetime(2026, 3, 8, 3, 57, 20, 348000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.0,
  36.5,
  54.0,
  1012.8,
  False,
  74.0,
  1.0),
 ('Y2026R01S5',
  58,
  3433.74,
  datetime.datetime(2026, 3, 8, 3, 58, 20, 363000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.0,
  36.0,
  54.2,
  1012.8,
  False,
  116.0,
  4.6),
 ('Y2026R01S5',
  59,
  3493.747,
  datetime.datetime(2026, 3, 8, 3, 59, 20, 370000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.9,
  35.4,
  53.8,
  1013.0,
  False,
  93.0,
  3.1),
 ('Y2026R01S5',
  60,
  3553.745,
  datetime.datetime(2026, 3, 8, 4, 0, 20, 368000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.9,
  35.7,
  54.3,
  1012.8,
  False,
  100.0,
  2.1),
 ('Y2026R01S5',
  61,
  3613.732,
  datetime.datetime(2026, 3, 8, 4, 1, 20, 355000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.9,
  35.3,
  54.2,
  1012.9,
  False,
  185.0,
  1.8),
 ('Y2026R01S5',
  62,
  3673.76,
  datetime.datetime(2026, 3, 8, 4, 2, 20, 383000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  23.9,
  37.5,
  54.2,
  1012.8,
  False,
  99.0,
  2.5),
 ('Y2026R01S5',
  63,
  3733.761,
  datetime.datetime(2026, 3, 8, 4, 3, 20, 384000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.0,
  38.0,
  54.0,
  1012.9,
  False,
  129.0,
  3.4),
 ('Y2026R01S5',
  64,
  3793.796,
  datetime.datetime(2026, 3, 8, 4, 4, 20, 419000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.2,
  36.6,
  54.0,
  1012.8,
  False,
  104.0,
  4.4),
 ('Y2026R01S5',
  65,
  3853.794,
  datetime.datetime(2026, 3, 8, 4, 5, 20, 417000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.2,
  36.0,
  54.4,
  1012.8,
  False,
  135.0,
  2.3),
 ('Y2026R01S5',
  66,
  3913.794,
  datetime.datetime(2026, 3, 8, 4, 6, 20, 417000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.1,
  36.1,
  54.1,
  1012.9,
  False,
  112.0,
  1.6),
 ('Y2026R01S5',
  67,
  3973.816,
  datetime.datetime(2026, 3, 8, 4, 7, 20, 439000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.1,
  36.1,
  54.1,
  1012.9,
  False,
  112.0,
  1.6),
 ('Y2026R01S5',
  68,
  4033.811,
  datetime.datetime(2026, 3, 8, 4, 8, 20, 434000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.1,
  36.1,
  54.1,
  1012.9,
  False,
  112.0,
  1.6),
 ('Y2026R01S5',
  69,
  4093.824,
  datetime.datetime(2026, 3, 8, 4, 9, 20, 447000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.1,
  36.1,
  54.1,
  1012.9,
  False,
  112.0,
  1.6),
 ('Y2026R01S5',
  70,
  4153.828,
  datetime.datetime(2026, 3, 8, 4, 10, 20, 451000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.2,
  35.1,
  54.2,
  1012.8,
  False,
  127.0,
  2.2),
 ('Y2026R01S5',
  71,
  4213.83,
  datetime.datetime(2026, 3, 8, 4, 11, 20, 453000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.2,
  35.3,
  54.3,
  1012.6,
  False,
  114.0,
  2.7),
 ('Y2026R01S5',
  72,
  4273.82,
  datetime.datetime(2026, 3, 8, 4, 12, 20, 443000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.2,
  35.1,
  54.7,
  1012.6,
  False,
  99.0,
  3.4),
 ('Y2026R01S5',
  73,
  4333.833,
  datetime.datetime(2026, 3, 8, 4, 13, 20, 456000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.3,
  35.8,
  54.6,
  1012.5,
  False,
  121.0,
  2.0),
 ('Y2026R01S5',
  74,
  4393.821,
  datetime.datetime(2026, 3, 8, 4, 14, 20, 444000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.5,
  36.6,
  54.3,
  1012.6,
  False,
  104.0,
  2.4),
 ('Y2026R01S5',
  75,
  4453.832,
  datetime.datetime(2026, 3, 8, 4, 15, 20, 455000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.4,
  38.1,
  53.7,
  1012.6,
  False,
  121.0,
  3.1),
 ('Y2026R01S5',
  76,
  4513.832,
  datetime.datetime(2026, 3, 8, 4, 16, 20, 455000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.4,
  37.6,
  53.1,
  1012.5,
  False,
  122.0,
  2.4),
 ('Y2026R01S5',
  77,
  4573.833,
  datetime.datetime(2026, 3, 8, 4, 17, 20, 456000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.5,
  36.7,
  53.3,
  1012.6,
  False,
  119.0,
  1.6),
 ('Y2026R01S5',
  78,
  4633.861,
  datetime.datetime(2026, 3, 8, 4, 18, 20, 484000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.4,
  36.6,
  53.1,
  1012.4,
  False,
  128.0,
  2.7),
 ('Y2026R01S5',
  79,
  4693.852,
  datetime.datetime(2026, 3, 8, 4, 19, 20, 475000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.4,
  36.4,
  53.3,
  1012.5,
  False,
  113.0,
  2.2),
 ('Y2026R01S5',
  80,
  4753.868,
  datetime.datetime(2026, 3, 8, 4, 20, 20, 491000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.5,
  36.5,
  53.5,
  1012.4,
  False,
  128.0,
  2.0),
 ('Y2026R01S5',
  81,
  4813.86,
  datetime.datetime(2026, 3, 8, 4, 21, 20, 483000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.5,
  36.5,
  53.5,
  1012.4,
  False,
  128.0,
  2.0),
 ('Y2026R01S5',
  82,
  4873.87,
  datetime.datetime(2026, 3, 8, 4, 22, 20, 493000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.6,
  36.8,
  52.3,
  1012.4,
  False,
  113.0,
  2.0),
 ('Y2026R01S5',
  83,
  4933.906,
  datetime.datetime(2026, 3, 8, 4, 23, 20, 529000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.4,
  36.6,
  52.4,
  1012.4,
  False,
  95.0,
  3.8),
 ('Y2026R01S5',
  84,
  4993.903,
  datetime.datetime(2026, 3, 8, 4, 24, 20, 526000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.3,
  36.6,
  53.3,
  1012.4,
  False,
  114.0,
  2.5),
 ('Y2026R01S5',
  85,
  5053.917,
  datetime.datetime(2026, 3, 8, 4, 25, 20, 540000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.3,
  37.3,
  53.7,
  1012.3,
  False,
  125.0,
  2.0),
 ('Y2026R01S5',
  86,
  5113.908,
  datetime.datetime(2026, 3, 8, 4, 26, 20, 531000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.3,
  38.4,
  53.9,
  1012.3,
  False,
  140.0,
  3.5),
 ('Y2026R01S5',
  87,
  5173.916,
  datetime.datetime(2026, 3, 8, 4, 27, 20, 539000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.5,
  39.1,
  53.5,
  1012.3,
  False,
  119.0,
  3.0),
 ('Y2026R01S5',
  88,
  5233.92,
  datetime.datetime(2026, 3, 8, 4, 28, 20, 543000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.6,
  37.7,
  53.1,
  1012.3,
  False,
  111.0,
  3.0),
 ('Y2026R01S5',
  89,
  5293.918,
  datetime.datetime(2026, 3, 8, 4, 29, 20, 541000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.6,
  36.7,
  52.5,
  1012.3,
  False,
  138.0,
  4.1),
 ('Y2026R01S5',
  90,
  5353.934,
  datetime.datetime(2026, 3, 8, 4, 30, 20, 557000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.6,
  36.3,
  53.1,
  1012.3,
  False,
  137.0,
  3.6),
 ('Y2026R01S5',
  91,
  5413.936,
  datetime.datetime(2026, 3, 8, 4, 31, 20, 559000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.7,
  35.9,
  53.0,
  1012.3,
  False,
  142.0,
  2.9),
 ('Y2026R01S5',
  92,
  5473.955,
  datetime.datetime(2026, 3, 8, 4, 32, 20, 578000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.7,
  35.9,
  53.3,
  1012.1,
  False,
  133.0,
  1.9),
 ('Y2026R01S5',
  93,
  5533.969,
  datetime.datetime(2026, 3, 8, 4, 33, 20, 592000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.6,
  35.8,
  53.4,
  1012.2,
  False,
  126.0,
  2.8),
 ('Y2026R01S5',
  94,
  5593.968,
  datetime.datetime(2026, 3, 8, 4, 34, 20, 591000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.6,
  35.7,
  53.3,
  1012.1,
  False,
  119.0,
  3.8),
 ('Y2026R01S5',
  95,
  5653.955,
  datetime.datetime(2026, 3, 8, 4, 35, 20, 578000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.6,
  35.9,
  53.1,
  1012.2,
  False,
  123.0,
  2.7),
 ('Y2026R01S5',
  96,
  5713.957,
  datetime.datetime(2026, 3, 8, 4, 36, 20, 580000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.6,
  36.4,
  52.8,
  1012.1,
  False,
  111.0,
  2.9),
 ('Y2026R01S5',
  97,
  5773.973,
  datetime.datetime(2026, 3, 8, 4, 37, 20, 596000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.5,
  36.6,
  52.9,
  1012.2,
  False,
  95.0,
  1.4),
 ('Y2026R01S5',
  98,
  5833.959,
  datetime.datetime(2026, 3, 8, 4, 38, 20, 582000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.6,
  37.0,
  53.4,
  1012.1,
  False,
  114.0,
  2.1),
 ('Y2026R01S5',
  99,
  5893.974,
  datetime.datetime(2026, 3, 8, 4, 39, 20, 597000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.7,
  37.5,
  53.0,
  1012.0,
  False,
  113.0,
  1.8),
 ('Y2026R01S5',
  100,
  5953.975,
  datetime.datetime(2026, 3, 8, 4, 40, 20, 598000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.8,
  37.6,
  52.6,
  1012.1,
  False,
  147.0,
  3.1),
 ('Y2026R01S5',
  101,
  6013.976,
  datetime.datetime(2026, 3, 8, 4, 41, 20, 599000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.8,
  37.4,
  52.7,
  1012.0,
  False,
  106.0,
  3.3),
 ('Y2026R01S5',
  102,
  6073.991,
  datetime.datetime(2026, 3, 8, 4, 42, 20, 614000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.9,
  37.1,
  52.1,
  1012.0,
  False,
  105.0,
  3.3),
 ('Y2026R01S5',
  103,
  6134.01,
  datetime.datetime(2026, 3, 8, 4, 43, 20, 633000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.8,
  36.5,
  52.0,
  1012.0,
  False,
  98.0,
  2.5),
 ('Y2026R01S5',
  104,
  6194.01,
  datetime.datetime(2026, 3, 8, 4, 44, 20, 633000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.8,
  36.3,
  52.8,
  1012.0,
  False,
  98.0,
  4.0),
 ('Y2026R01S5',
  105,
  6254.01,
  datetime.datetime(2026, 3, 8, 4, 45, 20, 633000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.8,
  36.1,
  52.8,
  1012.1,
  False,
  120.0,
  3.0),
 ('Y2026R01S5',
  106,
  6313.993,
  datetime.datetime(2026, 3, 8, 4, 46, 20, 616000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  24.9,
  36.1,
  53.4,
  1012.0,
  False,
  115.0,
  2.8),
 ('Y2026R01S5',
  107,
  6374.017,
  datetime.datetime(2026, 3, 8, 4, 47, 20, 640000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  25.3,
  36.1,
  53.7,
  1012.0,
  False,
  123.0,
  2.5),
 ('Y2026R01S5',
  108,
  6434.013,

In [159]:
with psycopg.connect(database_url) as conn:
    with conn.cursor() as cur:
        cur.execute('select * from race_control_messages  ; ')
        messages = cur.fetchall()
messages

[('Y2026R01S5',
  1,
  421.377,
  datetime.datetime(2026, 3, 8, 3, 8, 8, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'PINK HEAD PADDING MATERIAL MUST BE USED',
  None,
  nan,
  0.0),
 ('Y2026R01S5',
  2,
  1133.377,
  datetime.datetime(2026, 3, 8, 3, 20, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Track',
  'GREEN',
  'GREEN LIGHT - PIT EXIT OPEN',
  None,
  nan,
  1.0),
 ('Y2026R01S5',
  3,
  1215.377,
  datetime.datetime(2026, 3, 8, 3, 21, 22, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'DOUBLE YELLOW',
  'DOUBLE YELLOW IN TRACK SECTOR 6',
  None,
  6.0,
  1.0),
 ('Y2026R01S5',
  4,
  1218.377,
  datetime.datetime(2026, 3, 8, 3, 21, 25, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'CLEAR',
  'CLEAR IN TRACK SECTOR 6',
  None,
  6.0,
  1.0),
 ('Y2026R01S5',
  5,
  1219.377,
  datetime.datetime(2026, 3, 8, 3, 21, 26, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'YELLOW',
  'YELLOW IN TRACK SECTOR 7',
  None,
  7.0,
  1.0),
 ('Y2026R01S5',
  6,
  1243.377,
  datetime.datetime(2026, 3, 8, 3, 21, 50, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'DOUBLE YELLOW',
  'DOUBLE YELLOW IN TRACK SECTOR 6',
  None,
  6.0,
  1.0),
 ('Y2026R01S5',
  7,
  1244.377,
  datetime.datetime(2026, 3, 8, 3, 21, 51, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'DOUBLE YELLOW',
  'DOUBLE YELLOW IN TRACK SECTOR 7',
  None,
  7.0,
  1.0),
 ('Y2026R01S5',
  8,
  1252.377,
  datetime.datetime(2026, 3, 8, 3, 21, 59, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'MEDICAL CAR DEPLOYED',
  None,
  nan,
  1.0),
 ('Y2026R01S5',
  9,
  1732.377,
  datetime.datetime(2026, 3, 8, 3, 29, 59, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'YELLOW',
  'YELLOW IN TRACK SECTOR 20',
  None,
  20.0,
  1.0),
 ('Y2026R01S5',
  10,
  1733.377,
  datetime.datetime(2026, 3, 8, 3, 30, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'PIT EXIT CLOSED',
  None,
  nan,
  1.0),
 ('Y2026R01S5',
  11,
  1748.377,
  datetime.datetime(2026, 3, 8, 3, 30, 15, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'DOUBLE YELLOW',
  'DOUBLE YELLOW IN TRACK SECTOR 20',
  None,
  20.0,
  1.0),
 ('Y2026R01S5',
  12,
  1758.377,
  datetime.datetime(2026, 3, 8, 3, 30, 25, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'CLEAR',
  'CLEAR IN TRACK SECTOR 20',
  None,
  20.0,
  1.0),
 ('Y2026R01S5',
  13,
  1879.377,
  datetime.datetime(2026, 3, 8, 3, 32, 26, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'CLEAR',
  'CLEAR IN TRACK SECTOR 20',
  None,
  20.0,
  1.0),
 ('Y2026R01S5',
  14,
  1926.377,
  datetime.datetime(2026, 3, 8, 3, 33, 13, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'INCIDENT INVOLVING CAR 27 (HUL) NOTED - STARTING PROCEDURE INFRINGEMENT',
  None,
  nan,
  1.0),
 ('Y2026R01S5',
  15,
  2206.377,
  datetime.datetime(2026, 3, 8, 3, 37, 53, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'CLEAR',
  'CLEAR IN TRACK SECTOR 7',
  None,
  7.0,
  1.0),
 ('Y2026R01S5',
  16,
  2207.377,
  datetime.datetime(2026, 3, 8, 3, 37, 54, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'CLEAR',
  'CLEAR IN TRACK SECTOR 6',
  None,
  6.0,
  1.0),
 ('Y2026R01S5',
  17,
  2253.377,
  datetime.datetime(2026, 3, 8, 3, 38, 40, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'FIA STEWARDS: INCIDENT INVOLVING CAR 27 (HUL) UNDER INVESTIGATION - STARTING PROCEDURE INFRINGEMENT',
  None,
  nan,
  1.0),
 ('Y2026R01S5',
  18,
  2356.377,
  datetime.datetime(2026, 3, 8, 3, 40, 23, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'DOUBLE YELLOW',
  'DOUBLE YELLOW IN TRACK SECTOR 15',
  None,
  15.0,
  1.0),
 ('Y2026R01S5',
  19,
  2373.377,
  datetime.datetime(2026, 3, 8, 3, 40, 40, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'CLEAR',
  'CLEAR IN TRACK SECTOR 15',
  None,
  15.0,
  1.0),
 ('Y2026R01S5',
  20,
  2643.377,
  datetime.datetime(2026, 3, 8, 3, 45, 10, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'RISK OF RAIN FOR THE F1 RACE IS 0%',
  None,
  nan,
  1.0),
 ('Y2026R01S5',
  21,
  3264.377,
  datetime.datetime(2026, 3, 8, 3, 55, 31, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'FIA STEWARDS: INCIDENT INVOLVING CAR 27 (HUL) NO FURTHER ACTION - STARTING PROCEDURE INFRINGEMENT',
  None,
  nan,
  1.0),
 ('Y2026R01S5',
  22,
  3355.377,
  datetime.datetime(2026, 3, 8, 3, 57, 2, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'OVERTAKE DISABLED',
  None,
  nan,
  1.0),
 ('Y2026R01S5',
  23,
  3614.377,
  datetime.datetime(2026, 3, 8, 4, 1, 21, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'INCIDENT INVOLVING CAR 43 (COL) NOTED - STARTING PROCEDURE INFRINGEMENT',
  None,
  nan,
  1.0),
 ('Y2026R01S5',
  24,
  3739.377,
  datetime.datetime(2026, 3, 8, 4, 3, 26, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Track',
  'GREEN',
  'GREEN LIGHT - PIT EXIT OPEN',
  None,
  nan,
  1.0),
 ('Y2026R01S5',
  25,
  3766.377,
  datetime.datetime(2026, 3, 8, 4, 3, 53, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'FIA STEWARDS: INCIDENT INVOLVING CAR 43 (COL) UNDER INVESTIGATION - STARTING PROCEDURE INFRINGEMENT',
  None,
  nan,
  1.0),
 ('Y2026R01S5',
  26,
  3819.377,
  datetime.datetime(2026, 3, 8, 4, 4, 46, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'OVERTAKE ENABLED',
  None,
  nan,
  1.0),
 ('Y2026R01S5',
  27,
  4204.377,
  datetime.datetime(2026, 3, 8, 4, 11, 11, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'CAR 10 (GAS) TIME 1:27.040 DELETED - TRACK LIMITS AT TURN 10 LAP 5 15:10:17',
  None,
  nan,
  6.0),
 ('Y2026R01S5',
  28,
  4280.377,
  datetime.datetime(2026, 3, 8, 4, 12, 27, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'CAR 5 (BOR) TIME 1:27.463 DELETED - TRACK LIMITS AT TURN 3 LAP 6 15:11:11',
  None,
  nan,
  7.0),
 ('Y2026R01S5',
  29,
  4389.377,
  datetime.datetime(2026, 3, 8, 4, 14, 16, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'FIA STEWARDS: STOP-AND-GO PENALTY FOR CAR 43 (COL) - STARTING PROCEDURE INFRINGEMENT',
  None,
  nan,
  8.0),
 ('Y2026R01S5',
  30,
  4503.377,
  datetime.datetime(2026, 3, 8, 4, 16, 10, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'TURN 11 INCIDENT INVOLVING CAR 16 (LEC) NOTED',
  None,
  nan,
  9.0),
 ('Y2026R01S5',
  31,
  4573.377,
  datetime.datetime(2026, 3, 8, 4, 17, 20, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'FIA STEWARDS: TURN 11 INCIDENT INVOLVING CAR 16 (LEC) REVIEWED NO FURTHER INVESTIGATION',
  None,
  nan,
  10.0),
 ('Y2026R01S5',
  32,
  4681.377,
  datetime.datetime(2026, 3, 8, 4, 19, 8, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'SafetyCar',
  'DEPLOYED',
  None,
  None,
  'VSC DEPLOYED',
  None,
  nan,
  12.0),
 ('Y2026R01S5',
  33,
  4689.377,
  datetime.datetime(2026, 3, 8, 4, 19, 16, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'YELLOW',
  'YELLOW IN TRACK SECTOR 13',
  None,
  13.0,
  12.0),
 ('Y2026R01S5',
  34,
  4692.377,
  datetime.datetime(2026, 3, 8, 4, 19, 19, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'DOUBLE YELLOW',
  'DOUBLE YELLOW IN TRACK SECTOR 13',
  None,
  13.0,
  12.0),
 ('Y2026R01S5',
  35,
  4742.377,
  datetime.datetime(2026, 3, 8, 4, 20, 9, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'MARSHALS ON TRACK AT TURN 9',
  None,
  nan,
  12.0),
 ('Y2026R01S5',
  36,
  4806.377,
  datetime.datetime(2026, 3, 8, 4, 21, 13, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'FIA STEWARDS: PENALTY SERVED - STOP-AND-GO PENALTY FOR CAR 43 (COL) - STARTING PROCEDURE INFRINGEMENT',
  None,
  nan,
  13.0),
 ('Y2026R01S5',
  37,
  4918.377,
  datetime.datetime(2026, 3, 8, 4, 23, 5, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'CLEAR',
  'CLEAR IN TRACK SECTOR 13',
  None,
  13.0,
  14.0),
 ('Y2026R01S5',
  38,
  4920.377,
  datetime.datetime(2026, 3, 8, 4, 23, 7, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'SafetyCar',
  'ENDING',
  None,
  None,
  'VSC ENDING',
  None,
  nan,
  14.0),
 ('Y2026R01S5',
  39,
  4932.377,
  datetime.datetime(2026, 3, 8, 4, 23, 19, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Track',
  'CLEAR',
  'TRACK CLEAR',
  None,
  nan,
  14.0),
 ('Y2026R01S5',
  40,
  4935.377,
  datetime.datetime(2026, 3, 8, 4, 23, 22, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 77 (BOT) TIMED AT 15:23:22',
  '77',
  nan,
  14.0),
 ('Y2026R01S5',
  41,
  4943.377,
  datetime.datetime(2026, 3, 8, 4, 23, 30, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 77 (BOT) TIMED AT 15:23:30',
  '77',
  nan,
  14.0),
 ('Y2026R01S5',
  42,
  4948.377,
  datetime.datetime(2026, 3, 8, 4, 23, 35, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 77 (BOT) TIMED AT 15:23:35',
  '77',
  nan,
  14.0),
 ('Y2026R01S5',
  43,
  4994.377,
  datetime.datetime(2026, 3, 8, 4, 24, 21, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 77 (BOT) TIMED AT 15:24:20',
  '77',
  nan,
  14.0),
 ('Y2026R01S5',
  44,
  5039.377,
  datetime.datetime(2026, 3, 8, 4, 25, 6, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 77 (BOT) TIMED AT 15:25:06',
  '77',
  nan,
  15.0),
 ('Y2026R01S5',
  45,
  5060.377,
  datetime.datetime(2026, 3, 8, 4, 25, 27, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 77 (BOT) TIMED AT 15:25:26',
  '77',
  nan,
  15.0),
 ('Y2026R01S5',
  46,
  5120.377,
  datetime.datetime(2026, 3, 8, 4, 26, 27, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 77 (BOT) TIMED AT 15:26:27',
  '77',
  nan,
  16.0),
 ('Y2026R01S5',
  47,
  5135.377,
  datetime.datetime(2026, 3, 8, 4, 26, 42, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 77 (BOT) TIMED AT 15:26:41',
  '77',
  nan,
  16.0),
 ('Y2026R01S5',
  48,
  5252.377,
  datetime.datetime(2026, 3, 8, 4, 28, 39, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'CAR 23 (ALB) TIME 1:28.434 DELETED - TRACK LIMITS AT TURN 3 LAP 16 15:26:48',
  None,
  nan,
  18.0),
 ('Y2026R01S5',
  49,
  5311.377,
  datetime.datetime(2026, 3, 8, 4, 29, 38, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'YELLOW',
  'YELLOW IN TRACK SECTOR 20',
  None,
  20.0,
  18.0),
 ('Y2026R01S5',
  50,
  5325.377,
  datetime.datetime(2026, 3, 8, 4, 29, 52, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 18 (STR) TIMED AT 15:29:51',
  '18',
  nan,
  18.0),
 ('Y2026R01S5',
  51,
  5328.377,
  datetime.datetime(2026, 3, 8, 4, 29, 55, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'SafetyCar',
  'DEPLOYED',
  None,
  None,
  'VSC DEPLOYED',
  None,
  nan,
  18.0),
 ('Y2026R01S5',
  52,
  5409.377,
  datetime.datetime(2026, 3, 8, 4, 31, 16, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'PIT LANE ENTRY CLOSED',
  None,
  nan,
  19.0),
 ('Y2026R01S5',
  53,
  5410.377,
  datetime.datetime(2026, 3, 8, 4, 31, 17, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Sector',
  'CLEAR',
  'CLEAR IN TRACK SECTOR 20',
  None,
  20.0,
  19.0),
 ('Y2026R01S5',
  54,
  5457.377,
  datetime.datetime(2026, 3, 8, 4, 32, 4, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'MARSHALS ON TRACK AT PIT ENTRY',
  None,
  nan,
  20.0),
 ('Y2026R01S5',
  55,
  5474.377,
  datetime.datetime(2026, 3, 8, 4, 32, 21, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'PIT LANE ENTRY OPEN',
  None,
  nan,
  20.0),
 ('Y2026R01S5',
  56,
  5479.377,
  datetime.datetime(2026, 3, 8, 4, 32, 26, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'SafetyCar',
  'ENDING',
  None,
  None,
  'VSC ENDING',
  None,
  nan,
  20.0),
 ('Y2026R01S5',
  57,
  5492.377,
  datetime.datetime(2026, 3, 8, 4, 32, 39, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Track',
  'CLEAR',
  'TRACK CLEAR',
  None,
  nan,
  20.0),
 ('Y2026R01S5',
  58,
  5496.377,
  datetime.datetime(2026, 3, 8, 4, 32, 43, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 18 (STR) TIMED AT 15:32:43',
  '18',
  nan,
  20.0),
 ('Y2026R01S5',
  59,
  5509.377,
  datetime.datetime(2026, 3, 8, 4, 32, 56, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 18 (STR) TIMED AT 15:32:55',
  '18',
  nan,
  20.0),
 ('Y2026R01S5',
  60,
  5594.377,
  datetime.datetime(2026, 3, 8, 4, 34, 21, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'TURN 11 INCIDENT INVOLVING CARS 11 (PER) AND 30 (LAW) NOTED - FORCING ANOTHER DRIVER OFF THE TRACK',
  None,
  nan,
  21.0),
 ('Y2026R01S5',
  61,
  5606.377,
  datetime.datetime(2026, 3, 8, 4, 34, 33, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 18 (STR) TIMED AT 15:34:33',
  '18',
  nan,
  21.0),
 ('Y2026R01S5',
  62,
  5641.377,
  datetime.datetime(2026, 3, 8, 4, 35, 8, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'CAR 30 (LAW) TIME 1:29.919 DELETED - TRACK LIMITS AT TURN 3 LAP 16 15:26:58',
  None,
  nan,
  22.0),
 ('Y2026R01S5',
  63,
  5697.377,
  datetime.datetime(2026, 3, 8, 4, 36, 4, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 11 (PER) TIMED AT 15:36:03',
  '11',
  nan,
  22.0),
 ('Y2026R01S5',
  64,
  5713.377,
  datetime.datetime(2026, 3, 8, 4, 36, 20, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 18 (STR) TIMED AT 15:36:20',
  '18',
  nan,
  22.0),
 ('Y2026R01S5',
  65,
  5720.377,
  datetime.datetime(2026, 3, 8, 4, 36, 27, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 11 (PER) TIMED AT 15:36:26',
  '11',
  nan,
  23.0),
 ('Y2026R01S5',
  66,
  5752.377,
  datetime.datetime(2026, 3, 8, 4, 36, 59, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'TURN 3 INCIDENT INVOLVING CARS 31 (OCO) AND 10 (GAS) NOTED',
  None,
  nan,
  23.0),
 ('Y2026R01S5',
  67,
  5785.377,
  datetime.datetime(2026, 3, 8, 4, 37, 32, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'FIA STEWARDS: TURN 11 INCIDENT INVOLVING CARS 11 (PER) AND 30 (LAW) UNDER INVESTIGATION - FORCING ANOTHER DRIVER OFF THE TRACK',
  None,
  nan,
  23.0),
 ('Y2026R01S5',
  68,
  5790.377,
  datetime.datetime(2026, 3, 8, 4, 37, 37, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 11 (PER) TIMED AT 15:37:36',
  '11',
  nan,
  23.0),
 ('Y2026R01S5',
  69,
  5843.377,
  datetime.datetime(2026, 3, 8, 4, 38, 30, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'FIA STEWARDS: TURN 3 INCIDENT INVOLVING CARS 31 (OCO) AND 10 (GAS) UNDER INVESTIGATION',
  None,
  nan,
  24.0),
 ('Y2026R01S5',
  70,
  5920.377,
  datetime.datetime(2026, 3, 8, 4, 39, 47, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 11 (PER) TIMED AT 15:39:46',
  '11',
  nan,
  25.0),
 ('Y2026R01S5',
  71,
  5929.377,
  datetime.datetime(2026, 3, 8, 4, 39, 56, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'INCIDENT INVOLVING CAR 31 (OCO) NOTED - DRIVING UNNECESSARILY SLOWLY',
  None,
  nan,
  25.0),
 ('Y2026R01S5',
  72,
  5982.377,
  datetime.datetime(2026, 3, 8, 4, 40, 49, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'FIA STEWARDS: TURN 11 INCIDENT INVOLVING CARS 11 (PER) AND 30 (LAW) NO FURTHER ACTION - FORCING ANOTHER DRIVER OFF THE TRACK',
  None,
  nan,
  26.0),
 ('Y2026R01S5',
  73,
  6040.377,
  datetime.datetime(2026, 3, 8, 4, 41, 47, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 18 (STR) TIMED AT 15:41:46',
  '18',
  nan,
  26.0),
 ('Y2026R01S5',
  74,
  6077.377,
  datetime.datetime(2026, 3, 8, 4, 42, 24, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 11 (PER) TIMED AT 15:42:24',
  '11',
  nan,
  27.0),
 ('Y2026R01S5',
  75,
  6100.377,
  datetime.datetime(2026, 3, 8, 4, 42, 47, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 18 (STR) TIMED AT 15:42:46',
  '18',
  nan,
  27.0),
 ('Y2026R01S5',
  76,
  6132.377,
  datetime.datetime(2026, 3, 8, 4, 43, 19, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'INCIDENT INVOLVING CAR 11 (PER) NOTED - IGNORING BLUE FLAGS',
  None,
  nan,
  27.0),
 ('Y2026R01S5',
  77,
  6173.377,
  datetime.datetime(2026, 3, 8, 4, 44, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 11 (PER) TIMED AT 15:43:59',
  '11',
  nan,
  28.0),
 ('Y2026R01S5',
  78,
  6213.377,
  datetime.datetime(2026, 3, 8, 4, 44, 40, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 18 (STR) TIMED AT 15:44:39',
  '18',
  nan,
  28.0),
 ('Y2026R01S5',
  79,
  6243.377,
  datetime.datetime(2026, 3, 8, 4, 45, 10, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 11 (PER) TIMED AT 15:45:10',
  '11',
  nan,
  29.0),
 ('Y2026R01S5',
  80,
  6293.377,
  datetime.datetime(2026, 3, 8, 4, 46, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 43 (COL) TIMED AT 15:45:59',
  '43',
  nan,
  29.0),
 ('Y2026R01S5',
  81,
  6297.377,
  datetime.datetime(2026, 3, 8, 4, 46, 4, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 43 (COL) TIMED AT 15:46:03',
  '43',
  nan,
  29.0),
 ('Y2026R01S5',
  82,
  6305.377,
  datetime.datetime(2026, 3, 8, 4, 46, 12, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 11 (PER) TIMED AT 15:46:11',
  '11',
  nan,
  30.0),
 ('Y2026R01S5',
  83,
  6348.377,
  datetime.datetime(2026, 3, 8, 4, 46, 55, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Other',
  None,
  None,
  None,
  'FIA STEWARDS: INCIDENT INVOLVING CAR 31 (OCO) WILL BE INVESTIGATED AFTER THE RACE - DRIVING UNNECESSARILY SLOWLY',
  None,
  nan,
  30.0),
 ('Y2026R01S5',
  84,
  6437.377,
  datetime.datetime(2026, 3, 8, 4, 48, 24, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 14 (ALO) TIMED AT 15:48:24',
  '14',
  nan,
  31.0),
 ('Y2026R01S5',
  85,
  6465.377,
  datetime.datetime(2026, 3, 8, 4, 48, 52, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  'Flag',
  None,
  'Driver',
  'BLUE',
  'WAVED BLUE FLAG FOR CAR 43 (COL) TIMED AT 15:48:52',
  '43',
  nan,
  31.0),
 ('Y2026R01S5',
  86,
  6505.377,

In [161]:
with psycopg.connect(database_url) as conn:
    with conn.cursor() as cur:
        cur.execute('select * from session_results  ; ')
        results = cur.fetchall()
results

[('Y2026R01S5',
  '63',
  'G RUSSELL',
  'RUS',
  'russell',
  'Mercedes',
  '#00d7b6',
  'mercedes',
  'George',
  'Russell',
  'George Russell',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GEORUS01_George_Russell/georus01.png.transform/1col/image.png',
  '',
  1.0,
  '1',
  1.0,
  None,
  None,
  None,
  4986.801,
  'Finished',
  25.0,
  58.0),
 ('Y2026R01S5',
  '12',
  'K ANTONELLI',
  'ANT',
  'antonelli',
  'Mercedes',
  '#00d7b6',
  'mercedes',
  'Kimi',
  'Antonelli',
  'Kimi Antonelli',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/K/ANDANT01_Kimi_Antonelli/andant01.png.transform/1col/image.png',
  '',
  2.0,
  '2',
  2.0,
  None,
  None,
  None,
  2.974,
  'Finished',
  18.0,
  58.0),
 ('Y2026R01S5',
  '16',
  'C LECLERC',
  'LEC',
  'leclerc',
  'Ferrari',
  '#ed1131',
  'ferrari',
  'Charles',
  'Leclerc',
  'Charles Leclerc',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png.transform/1col/image.png',
  '',
  3.0,
  '3',
  4.0,
  None,
  None,
  None,
  15.519,
  'Finished',
  15.0,
  58.0),
 ('Y2026R01S5',
  '44',
  'L HAMILTON',
  'HAM',
  'hamilton',
  'Ferrari',
  '#ed1131',
  'ferrari',
  'Lewis',
  'Hamilton',
  'Lewis Hamilton',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png.transform/1col/image.png',
  '',
  4.0,
  '4',
  7.0,
  None,
  None,
  None,
  16.144,
  'Finished',
  12.0,
  58.0),
 ('Y2026R01S5',
  '1',
  'L NORRIS',
  'NOR',
  'norris',
  'McLaren',
  '#f47600',
  'mclaren',
  'Lando',
  'Norris',
  'Lando Norris',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png.transform/1col/image.png',
  '',
  5.0,
  '5',
  6.0,
  None,
  None,
  None,
  51.741,
  'Finished',
  10.0,
  58.0),
 ('Y2026R01S5',
  '3',
  'M VERSTAPPEN',
  'VER',
  'max_verstappen',
  'Red Bull Racing',
  '#4781d7',
  'red_bull',
  'Max',
  'Verstappen',
  'Max Verstappen',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png.transform/1col/image.png',
  '',
  6.0,
  '6',
  20.0,
  None,
  None,
  None,
  54.617,
  'Finished',
  8.0,
  58.0),
 ('Y2026R01S5',
  '87',
  'O BEARMAN',
  'BEA',
  'bearman',
  'Haas F1 Team',
  '#9c9fa2',
  'haas',
  'Oliver',
  'Bearman',
  'Oliver Bearman',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OLIBEA01_Oliver_Bearman/olibea01.png.transform/1col/image.png',
  '',
  7.0,
  '7',
  12.0,
  None,
  None,
  None,
  4.593,
  'Lapped',
  6.0,
  57.0),
 ('Y2026R01S5',
  '41',
  'A LINDBLAD',
  'LIN',
  'arvid_lindblad',
  'Racing Bulls',
  '#6c98ff',
  'rb',
  'Arvid',
  'Lindblad',
  'Arvid Lindblad',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/A/ARVLIN01_Arvid_Lindblad/arvlin01.png.transform/1col/image.png',
  '',
  8.0,
  '8',
  9.0,
  None,
  None,
  None,
  11.816,
  'Lapped',
  4.0,
  57.0),
 ('Y2026R01S5',
  '5',
  'G BORTOLETO',
  'BOR',
  'bortoleto',
  'Audi',
  '#f50537',
  'audi',
  'Gabriel',
  'Bortoleto',
  'Gabriel Bortoleto',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/G/GABBOR01_Gabriel_Bortoleto/gabbor01.png.transform/1col/image.png',
  '',
  9.0,
  '9',
  10.0,
  None,
  None,
  None,
  12.775,
  'Lapped',
  2.0,
  57.0),
 ('Y2026R01S5',
  '10',
  'P GASLY',
  'GAS',
  'gasly',
  'Alpine',
  '#00a1e8',
  'alpine',
  'Pierre',
  'Gasly',
  'Pierre Gasly',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/P/PIEGAS01_Pierre_Gasly/piegas01.png.transform/1col/image.png',
  '',
  10.0,
  '10',
  14.0,
  None,
  None,
  None,
  29.027,
  'Lapped',
  1.0,
  57.0),
 ('Y2026R01S5',
  '31',
  'E OCON',
  'OCO',
  'ocon',
  'Haas F1 Team',
  '#9c9fa2',
  'haas',
  'Esteban',
  'Ocon',
  'Esteban Ocon',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/E/ESTOCO01_Esteban_Ocon/estoco01.png.transform/1col/image.png',
  '',
  11.0,
  '11',
  13.0,
  None,
  None,
  None,
  29.85,
  'Lapped',
  0.0,
  57.0),
 ('Y2026R01S5',
  '23',
  'A ALBON',
  'ALB',
  'albon',
  'Williams',
  '#1868db',
  'williams',
  'Alexander',
  'Albon',
  'Alexander Albon',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/A/ALEALB01_Alexander_Albon/alealb01.png.transform/1col/image.png',
  '',
  12.0,
  '12',
  15.0,
  None,
  None,
  None,
  56.075,
  'Lapped',
  0.0,
  57.0),
 ('Y2026R01S5',
  '30',
  'L LAWSON',
  'LAW',
  'lawson',
  'Racing Bulls',
  '#6c98ff',
  'rb',
  'Liam',
  'Lawson',
  'Liam Lawson',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LIALAW01_Liam_Lawson/lialaw01.png.transform/1col/image.png',
  '',
  13.0,
  '13',
  8.0,
  None,
  None,
  None,
  57.173,
  'Lapped',
  0.0,
  57.0),
 ('Y2026R01S5',
  '43',
  'F COLAPINTO',
  'COL',
  'colapinto',
  'Alpine',
  '#00a1e8',
  'alpine',
  'Franco',
  'Colapinto',
  'Franco Colapinto',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/F/FRACOL01_Franco_Colapinto/fracol01.png.transform/1col/image.png',
  '',
  14.0,
  '14',
  16.0,
  None,
  None,
  None,
  8.487,
  'Lapped',
  0.0,
  56.0),
 ('Y2026R01S5',
  '55',
  'C SAINZ',
  'SAI',
  'sainz',
  'Williams',
  '#1868db',
  'williams',
  'Carlos',
  'Sainz',
  'Carlos Sainz',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/C/CARSAI01_Carlos_Sainz/carsai01.png.transform/1col/image.png',
  '',
  15.0,
  '15',
  21.0,
  None,
  None,
  None,
  36.886,
  'Lapped',
  0.0,
  56.0),
 ('Y2026R01S5',
  '11',
  'S PEREZ',
  'PER',
  'perez',
  'Cadillac',
  '#909090',
  'cadillac',
  'Sergio',
  'Perez',
  'Sergio Perez',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png.transform/1col/image.png',
  '',
  16.0,
  '16',
  18.0,
  None,
  None,
  None,
  7.85,
  'Lapped',
  0.0,
  55.0),
 ('Y2026R01S5',
  '18',
  'L STROLL',
  'STR',
  'stroll',
  'Aston Martin',
  '#229971',
  'aston_martin',
  'Lance',
  'Stroll',
  'Lance Stroll',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/L/LANSTR01_Lance_Stroll/lanstr01.png.transform/1col/image.png',
  '',
  17.0,
  'R',
  22.0,
  None,
  None,
  None,
  None,
  'Lapped',
  0.0,
  43.0),
 ('Y2026R01S5',
  '14',
  'F ALONSO',
  'ALO',
  'alonso',
  'Aston Martin',
  '#229971',
  'aston_martin',
  'Fernando',
  'Alonso',
  'Fernando Alonso',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/F/FERALO01_Fernando_Alonso/feralo01.png.transform/1col/image.png',
  '',
  18.0,
  'R',
  17.0,
  None,
  None,
  None,
  None,
  'Retired',
  0.0,
  21.0),
 ('Y2026R01S5',
  '77',
  'V BOTTAS',
  'BOT',
  'bottas',
  'Cadillac',
  '#909090',
  'cadillac',
  'Valtteri',
  'Bottas',
  'Valtteri Bottas',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/V/VALBOT01_Valtteri_Bottas/valbot01.png.transform/1col/image.png',
  '',
  19.0,
  'R',
  19.0,
  None,
  None,
  None,
  None,
  'Retired',
  0.0,
  15.0),
 ('Y2026R01S5',
  '6',
  'I HADJAR',
  'HAD',
  'hadjar',
  'Red Bull Racing',
  '#4781d7',
  'red_bull',
  'Isack',
  'Hadjar',
  'Isack Hadjar',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/I/ISAHAD01_Isack_Hadjar/isahad01.png.transform/1col/image.png',
  '',
  20.0,
  'R',
  3.0,
  None,
  None,
  None,
  None,
  'Retired',
  0.0,
  10.0),
 ('Y2026R01S5',
  '81',
  'O PIASTRI',
  'PIA',
  'piastri',
  'McLaren',
  '#f47600',
  'mclaren',
  'Oscar',
  'Piastri',
  'Oscar Piastri',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OSCPIA01_Oscar_Piastri/oscpia01.png.transform/1col/image.png',
  '',
  21.0,
  'W',
  5.0,
  None,
  None,
  None,
  None,
  'Did not start',
  0.0,
  0.0),
 ('Y2026R01S5',
  '27',
  'N HULKENBERG',
  'HUL',
  'hulkenberg',
  'Audi',
  '#f50537',
  'audi',
  'Nico',
  'Hulkenberg',
  'Nico Hulkenberg',
  'https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/N/NICHUL01_Nico_Hulkenberg/nichul01.png.transform/1col/image.png',
  '',
  22.0,
  'W',
  11.0,
  None,
  None,
  None,
  None,
  'Did not start',
  0.0,
  0.0)]

In [175]:
with psycopg.connect(database_url) as conn:
    with conn.cursor() as cur:
        cur.execute('select timestamp_lap_start_absolute, timestamp_lap_end_absolute from session_laps  ; ')
        laps = cur.fetchall()
laps

[(datetime.datetime(2026, 3, 8, 4, 3, 26, 366000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 5, 3, 60000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 5, 3, 60000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 6, 30, 404000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 6, 30, 404000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 7, 57, 267000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 7, 57, 267000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 9, 23, 124000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 9, 23, 124000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 10, 48, 697000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 10, 48, 697000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 12, 13, 733000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 12, 13, 733000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 13, 38, 711000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 13, 38, 711000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 15, 4, 10000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 15, 4, 10000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 16, 29, 649000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 16, 29, 649000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 17, 54, 944000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 17, 54, 944000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 19, 38, 335000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 19, 38, 335000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 21, 36, 410000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 21, 36, 410000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 23, 28, 342000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 23, 28, 342000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 24, 52, 575000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 24, 52, 575000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 26, 16, 359000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 26, 16, 359000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 27, 40, 271000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 27, 40, 271000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 29, 4, 324000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 29, 4, 324000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 30, 39, 728000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 30, 39, 728000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 32, 35, 798000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 32, 35, 798000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 34, 1, 572000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 34, 1, 572000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 35, 25, 544000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 35, 25, 544000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 36, 49, 231000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 36, 49, 231000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 38, 12, 765000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 38, 12, 765000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 39, 36, 159000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 39, 36, 159000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 40, 59, 659000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 40, 59, 659000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 42, 23, 62000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 42, 23, 62000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 43, 46, 958000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 43, 46, 958000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 45, 10, 998000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 45, 10, 998000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 46, 35, 78000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 46, 35, 78000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 47, 59, 39000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 47, 59, 39000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 49, 23, 133000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 49, 23, 133000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 50, 47, 208000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 50, 47, 208000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 52, 11, 998000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 52, 11, 998000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 54, 4, 730000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 54, 4, 730000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 55, 34, 164000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 55, 34, 164000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 56, 57, 488000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 56, 57, 488000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 58, 20, 936000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 58, 20, 936000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 59, 44, 359000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 59, 44, 359000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 1, 8, 360000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 1, 8, 360000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 2, 31, 757000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 2, 31, 757000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 3, 55, 519000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 3, 55, 519000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 5, 18, 866000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 5, 18, 866000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 6, 42, 152000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 6, 42, 152000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 8, 5, 344000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 8, 5, 344000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 9, 28, 230000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 9, 28, 230000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 10, 51, 138000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 10, 51, 138000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 12, 13, 916000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 12, 13, 916000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 13, 36, 869000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 13, 36, 869000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 14, 59, 673000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 14, 59, 673000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 16, 22, 436000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 16, 22, 436000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 17, 45, 34000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 17, 45, 34000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 19, 7, 818000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 19, 7, 818000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 20, 30, 176000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 20, 30, 176000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 21, 52, 972000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 21, 52, 972000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 23, 15, 839000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 23, 15, 839000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 24, 38, 682000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 24, 38, 682000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 26, 2, 98000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 26, 2, 98000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 27, 25, 144000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 3, 26, 366000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 5, 4, 582000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 5, 4, 582000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 6, 31, 863000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 6, 31, 863000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 7, 58, 234000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 7, 58, 234000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 9, 24, 128000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 9, 24, 128000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 10, 51, 168000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 10, 51, 168000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 12, 17, 157000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 12, 17, 157000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 13, 42, 236000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 13, 42, 236000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 15, 7, 200000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 15, 7, 200000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 16, 32, 641000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 16, 32, 641000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 17, 59, 310000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 17, 59, 310000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 19, 44, 131000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 19, 44, 131000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 21, 42, 203000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 21, 42, 203000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 23, 33, 837000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 23, 33, 837000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 24, 59, 585000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 24, 59, 585000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 26, 24, 408000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 26, 24, 408000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 27, 49, 98000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 27, 49, 98000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 29, 14, 301000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 29, 14, 301000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 30, 55, 526000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 30, 55, 526000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 32, 48, 476000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 32, 48, 476000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 34, 15, 54000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 34, 15, 54000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 35, 40, 732000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 35, 40, 732000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 37, 5, 318000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 37, 5, 318000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 38, 29, 817000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 38, 29, 817000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 39, 54, 669000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 39, 54, 669000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 41, 19, 209000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 41, 19, 209000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 42, 43, 980000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 42, 43, 980000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 44, 8, 641000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 44, 8, 641000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 45, 33, 436000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 45, 33, 436000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 46, 58, 532000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 46, 58, 532000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 48, 23, 774000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 48, 23, 774000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 49, 49, 45000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 49, 49, 45000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 51, 14, 247000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 51, 14, 247000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 52, 46, 523000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 52, 46, 523000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 54, 17, 767000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 54, 17, 767000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 55, 42, 796000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 55, 42, 796000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 57, 7, 973000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 57, 7, 973000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 4, 58, 34, 306000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 4, 58, 34, 306000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 0, 0, 400000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 0, 0, 400000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 1, 25, 665000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 1, 25, 665000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 2, 51, 797000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 2, 51, 797000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 4, 17, 116000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 4, 17, 116000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 5, 41, 995000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 5, 41, 995000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 7, 6, 972000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 7, 6, 972000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 8, 32, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 8, 32, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 9, 59, 175000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 9, 59, 175000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 11, 24, 528000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 11, 24, 528000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 12, 51, 25000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 12, 51, 25000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 14, 16, 7000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 14, 16, 7000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),
  datetime.datetime(2026, 3, 8, 5, 15, 41, 288000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (datetime.datetime(2026, 3, 8, 5, 15, 41, 288000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')),

In [176]:
[x for x in laps if not x[0]]

[(None,
  datetime.datetime(2026, 3, 8, 4, 18, 59, 615000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC'))),
 (None,
  datetime.datetime(2026, 3, 8, 4, 29, 34, 654000, tzinfo=zoneinfo.ZoneInfo(key='Etc/UTC')))]

In [167]:
session.laps['LapStartDate'].isna().sum()

np.int64(3)

In [170]:
bool(session.laps[session.laps['LapStartDate'].isna()]['LapStartDate'].iloc[0])

True

In [172]:
session.laps[session.laps['LapStartDate'].isna()]['LapStartDate'].iloc[0].isoformat()

'NaT'

In [185]:
session.session_status

                    Time     Status
0 0 days 00:00:04.500000   Inactive
1 0 days 01:02:32.281000    Started
2 0 days 02:30:48.262000   Finished
3 0 days 02:40:16.088000  Finalised
4 0 days 02:40:16.088000       Ends

In [192]:
vars(session.get_circuit_info()).keys()

dict_keys(['corners', 'marshal_lights', 'marshal_sectors', 'rotation'])

In [194]:
help(session.get_circuit_info().add_marker_distance)

Help on method add_marker_distance in module fastf1.mvapi.data:

add_marker_distance(reference_lap: 'fastf1.core.Lap') method of fastf1.mvapi.data.CircuitInfo instance
    :meta private:
    Computes the 'Distance' value for each track marker using the
    telemetry data of a provided reference lap.

    The distance values are computed using a best-fit approach by selecting
    the distance value of a telemetry sample, where the squared error of
    the xy-coordinates between telemetry data and track marker position
    is minimal.

In [196]:
a = session.get_circuit_info().add_marker_distance(session.laps.iloc[15])
type(a)

NoneType

In [207]:
session.get_circuit_info().marshal_sectors

              X             Y  Number Letter       Angle     Distance
0   3353.000000    920.000000       1          12.449547     3.301478
1   3515.829834  -2271.817871       2         -88.066845   362.781002
2   1691.748535  -1529.987549       3        -127.796402   564.018469
3    610.779236    219.528168       4          38.205092   794.632592
4   -800.530701   1781.093994       5        -158.226301  1017.890756
5   -924.145569   3118.867188       6          -3.327263  1152.638813
6  -2150.709229   4427.268555       7        -157.350991  1358.323214
7  -2446.911377   7329.717773       8         178.768374  1664.688611
8  -2148.736084   9516.055664       9         166.635973  1886.686837
9   -992.291138  11368.494141      10         -14.678034  2111.034902
10  -618.041992  15255.431641      11        -170.153010  2513.415207
11  -215.560059  15299.304688      12          22.633458  2830.019389
12  1076.745117  12104.976562      13        -161.929117  3195.678588
13  2311.971436   6950.871582      14          13.294185  3716.358495
14  2477.773682   4353.195312      15        -165.319878  3990.874567

In [204]:
session.get_circuit_info().rotation

62.0

In [199]:
session.laps.iloc[15].get_pos_data()

,Date,Status,X,Y,Z,Source,Time,SessionTime
0,2026-05-24 20:30:13.866,OnTrack,3407.0,1039.0,130.0,pos,0 days 00:00:00.146000,0 days 01:22:58.392000
1,2026-05-24 20:30:14.146,OnTrack,3421.0,979.0,130.0,pos,0 days 00:00:00.426000,0 days 01:22:58.672000
2,2026-05-24 20:30:14.306,OnTrack,3429.0,945.0,130.0,pos,0 days 00:00:00.586000,0 days 01:22:58.832000
3,2026-05-24 20:30:14.486,OnTrack,3438.0,906.0,130.0,pos,0 days 00:00:00.766000,0 days 01:22:59.012000
4,2026-05-24 20:30:14.826,OnTrack,3454.0,833.0,130.0,pos,0 days 00:00:01.106000,0 days 01:22:59.352000
...,...,...,...,...,...,...,...,...
306,2026-05-24 20:31:35.686,OnTrack,3161.0,1785.0,128.0,pos,0 days 00:01:21.966000,0 days 01:24:20.212000
307,2026-05-24 20:31:35.906,OnTrack,3205.0,1616.0,129.0,pos,0 days 00:01:22.186000,0 days 01:24:20.432000
308,2026-05-24 20:31:36.006,OnTrack,3223.0,1542.0,129.0,pos,0 days 00:01:22.286000,0 days 01:24:20.532000
309,2026-05-24 20:31:36.326,OnTrack,3303.0,1198.0,129.0,pos,0 days 00:01:22.606000,0 days 01:24:20.852000
310,2026-05-24 20:31:36.787,OnTrack,3352.0,925.0,131.0,pos,0 days 00:01:23.067000,0 days 01:24:21.313000

In [190]:
session.weather_data

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:31.031000,12.4,74.4,1025.5,False,17.2,185,5.7
1,0 days 00:01:31.028000,12.6,74.4,1025.5,False,17.2,185,5.7
2,0 days 00:02:31.033000,12.6,74.4,1025.5,False,17.2,185,5.7
3,0 days 00:03:31.017000,12.6,74.4,1025.5,False,17.2,185,5.7
4,0 days 00:04:31.030000,12.3,74.4,1025.5,False,17.2,185,5.7
...,...,...,...,...,...,...,...,...
155,0 days 02:35:31.777000,13.4,66.8,1023.1,False,18.1,184,2.8
156,0 days 02:36:31.762000,13.5,66.9,1023.0,False,17.8,168,5.4
157,0 days 02:37:31.762000,13.4,66.9,1023.0,False,17.8,168,5.4
158,0 days 02:38:31.766000,13.3,66.9,1023.0,False,17.8,168,5.4
159,0 days 02:39:31.770000,13.4,67.8,1023.1,False,18.0,183,3.1

In [187]:
session.session_start_time

datetime.timedelta(seconds=3752, microseconds=281000)

In [184]:
session.get_circuit_info().corners

              X             Y  Number Letter       Angle     Distance
0   3314.213623  -1317.854858       1        -165.704223   220.393040
1   3856.566650  -2073.488770       2         -22.292629   322.789897
2    740.000488   -608.991943       3        -158.882111   703.628954
3    746.362305    -42.993057       4          10.981968   767.648778
4   -724.044739   1618.967407       5          29.699708  1001.501773
5   -993.916626   3790.888672       6          27.681895  1208.853614
6  -1783.871460   4016.300781       7        -117.805015  1304.705839
7  -1785.440430  10539.706055       8         118.593733  1992.345289
8  -1140.291992  10976.314453       9         -28.305198  2076.504352
9   -711.505371  16759.564453      10          97.796495  2669.549972
10  -374.826996  15840.400391      11           9.367721  2769.842814
11   975.872559  12421.172852      12        -161.170043  3155.680166
12  2586.933350   5440.833008      13         -21.168127  3870.265278
13  2435.436279   5153.829590      14         157.077799  3907.526294

In [189]:
session.car_data['1']

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2026-05-24 19:08:02.716,0.0,0.0,0,0.0,False,0,car,0 days 00:00:47.242000,0 days 00:00:47.242000
1,2026-05-24 19:08:03.036,0.0,0.0,0,0.0,False,0,car,0 days 00:00:47.562000,0 days 00:00:47.562000
2,2026-05-24 19:08:03.316,0.0,0.0,0,0.0,False,0,car,0 days 00:00:47.842000,0 days 00:00:47.842000
3,2026-05-24 19:08:03.516,0.0,0.0,0,0.0,False,0,car,0 days 00:00:48.042000,0 days 00:00:48.042000
4,2026-05-24 19:08:03.716,0.0,0.0,0,0.0,False,0,car,0 days 00:00:48.242000,0 days 00:00:48.242000
...,...,...,...,...,...,...,...,...,...,...
34522,2026-05-24 21:42:39.910,0.0,0.0,0,104.0,True,0,car,0 days 02:35:24.436000,0 days 02:35:24.436000
34523,2026-05-24 21:42:40.150,0.0,0.0,0,104.0,True,0,car,0 days 02:35:24.676000,0 days 02:35:24.676000
34524,2026-05-24 21:42:40.429,0.0,0.0,0,104.0,True,0,car,0 days 02:35:24.955000,0 days 02:35:24.955000
34525,2026-05-24 21:42:40.629,0.0,0.0,0,104.0,True,0,car,0 days 02:35:25.155000,0 days 02:35:25.155000
34526,2026-05-24 21:42:40.829,0.0,0.0,0,104.0,True,0,car,0 days 02:35:25.355000,0 days 02:35:25.355000

In [179]:
session.laps.iloc[0].get_car_data()

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2026-05-24 20:09:47.850,12271.0,0.0,1,23.0,True,0,car,0 days 00:00:00.095000,0 days 01:02:32.376000
1,2026-05-24 20:09:48.170,12068.0,0.0,1,23.0,True,0,car,0 days 00:00:00.415000,0 days 01:02:32.696000
2,2026-05-24 20:09:48.410,10388.0,7.0,1,22.0,False,0,car,0 days 00:00:00.655000,0 days 01:02:32.936000
3,2026-05-24 20:09:48.730,8148.0,17.0,1,22.0,False,0,car,0 days 00:00:00.975000,0 days 01:02:33.256000
4,2026-05-24 20:09:48.930,6748.0,24.0,1,23.0,False,0,car,0 days 00:00:01.175000,0 days 01:02:33.456000
...,...,...,...,...,...,...,...,...,...,...
322,2026-05-24 20:11:13.049,11642.0,274.0,7,100.0,False,0,car,0 days 00:01:25.294000,0 days 01:03:57.575000
323,2026-05-24 20:11:13.290,11654.0,276.0,7,100.0,False,0,car,0 days 00:01:25.535000,0 days 01:03:57.816000
324,2026-05-24 20:11:13.530,11679.0,278.0,7,100.0,False,0,car,0 days 00:01:25.775000,0 days 01:03:58.056000
325,2026-05-24 20:11:13.850,11750.0,280.0,7,100.0,False,0,car,0 days 00:01:26.095000,0 days 01:03:58.376000
326,2026-05-24 20:11:14.010,11679.0,279.0,7,100.0,False,0,car,0 days 00:01:26.255000,0 days 01:03:58.536000

In [213]:
import pandas as pd

cols = ['session_id', 'feature_type', 'number', 'letter', 'coordinate_x', 'coordinate_y', 'angle', 'distance']
with psycopg.connect(database_url) as conn:
    with conn.cursor() as cur:
        cur.execute(f'select {",".join(cols)} from circuit_features  ; ')
        circuit_features = cur.fetchall()
circuit_features = pd.DataFrame(circuit_features, columns=cols)
circuit_features

,session_id,feature_type,number,letter,coordinate_x,coordinate_y,angle,distance
0,Y2026R01S5,corner,1,,-3650.594482,1193.784180,-176.632730,353.883741
1,Y2026R01S5,corner,2,,-3555.053223,1992.750244,-1.517007,436.700337
2,Y2026R01S5,corner,3,,-7194.970215,7101.942383,162.258315,1082.289274
3,Y2026R01S5,corner,4,,-5878.734375,7709.864746,-23.426263,1240.170991
4,Y2026R01S5,corner,5,,-5870.662598,9676.805664,159.215959,1435.149386
5,Y2026R01S5,corner,6,,-2280.641357,11861.559570,96.736266,1864.705500
6,Y2026R01S5,corner,7,,-1296.382446,11398.008789,-104.065903,1987.203085
7,Y2026R01S5,corner,8,,502.412537,10576.311523,39.145642,2157.206134
8,Y2026R01S5,corner,9,,2838.843750,798.959839,-101.197334,3279.161824
9,Y2026R01S5,corner,10,,3973.896484,855.019897,73.476771,3383.648575
10,Y2026R01S5,corner,11,,7489.130859,-4851.345215,-15.779635,4087.765440
11,Y2026R01S5,corner,12,,5020.217773,-5538.887695,-106.082895,4359.092824
12,Y2026R01S5,corner,13,,3587.226562,-3634.000000,89.839297,4608.497211
13,Y2026R01S5,corner,14,,2300.284180,-4454.023438,-97.403246,4764.984350
14,Y2026R01S5,marshal_light,1,,-1200.067871,-1327.125610,-132.857283,5231.080879
15,Y2026R01S5,marshal_light,2,,-2891.360596,276.744019,-133.358423,229.342290
16,Y2026R01S5,marshal_light,3,,-3788.004395,2744.416992,35.097031,507.785019
17,Y2026R01S5,marshal_light,4,,-5157.834961,4075.304443,-135.791112,721.059425
18,Y2026R01S5,marshal_light,5,,-6885.134766,6285.975586,-146.392665,996.258358
19,Y2026R01S5,marshal_light,6,,-6320.723145,7395.816895,-73.566602,1175.728955
20,Y2026R01S5,marshal_light,7,,-5947.000000,9210.094727,-177.905505,1371.673679
21,Y2026R01S5,marshal_light,8,,-4926.849121,10590.990234,122.445109,1568.623102
22,Y2026R01S5,marshal_light,9,,-3474.698242,11290.357422,113.415767,1716.260427
23,Y2026R01S5,marshal_light,10,,-504.105743,11226.028320,74.131091,2046.261061
24,Y2026R01S5,marshal_light,11,,1149.624146,8755.153320,7.053658,2380.257092
25,Y2026R01S5,marshal_light,12,,494.332825,5779.241211,154.510411,2685.061322
26,Y2026R01S5,marshal_light,13,,406.413727,3616.448486,-166.116110,2883.863172
27,Y2026R01S5,marshal_light,14,,1989.657959,1349.301636,-129.506926,3154.730686
28,Y2026R01S5,marshal_light,15,,3527.994629,848.884521,91.527126,3341.646954
29,Y2026R01S5,marshal_light,16,,6420.017090,-1352.264893,29.399328,3716.043495
30,Y2026R01S5,marshal_light,17,,7195.363770,-3446.331055,18.130106,3953.442346
31,Y2026R01S5,marshal_light,18,,6079.745117,-5367.668457,-74.968594,4258.121615
32,Y2026R01S5,marshal_light,19,,3962.527588,-4043.965332,27.309108,4552.800388
33,Y2026R01S5,marshal_light,20,,2935.000000,-4245.717285,-43.691578,4701.184036
34,Y2026R01S5,marshal_sector,1,,-1185.000000,-1341.000000,-128.917932,5231.080879
35,Y2026R01S5,marshal_sector,2,,-2897.316162,282.370392,-133.397702,229.342290
36,Y2026R01S5,marshal_sector,3,,-3816.246826,2784.653076,34.946842,535.144340
37,Y2026R01S5,marshal_sector,4,,-5106.551758,4022.321289,-136.082329,703.956746
38,Y2026R01S5,marshal_sector,5,,-6851.272949,6234.699219,-146.255169,984.416789
39,Y2026R01S5,marshal_sector,6,,-6348.359375,7388.174805,-75.580255,1175.728955
40,Y2026R01S5,marshal_sector,7,,-5947.000000,9210.094727,179.879527,1371.673679
41,Y2026R01S5,marshal_sector,8,,-4930.307129,10588.793945,123.768116,1568.623102
42,Y2026R01S5,marshal_sector,9,,-3455.983643,11298.679688,114.643064,1716.260427
43,Y2026R01S5,marshal_sector,10,,-375.090179,11185.664062,72.486372,2058.052363
44,Y2026R01S5,marshal_sector,11,,1152.093262,8734.820312,6.960332,2380.257092
45,Y2026R01S5,marshal_sector,12,,531.935913,5861.136230,155.920379,2649.161618
46,Y2026R01S5,marshal_sector,13,,381.896729,3724.301514,-167.228995,2883.863172
47,Y2026R01S5,marshal_sector,14,,2043.370483,1304.975830,-129.640054,3184.055466
48,Y2026R01S5,marshal_sector,15,,3740.939697,854.520142,91.479083,3364.021545
49,Y2026R01S5,marshal_sector,16,,6430.112305,-1370.088989,29.552476,3716.043495
50,Y2026R01S5,marshal_sector,17,,7169.928223,-3368.449707,18.113525,3935.990397
51,Y2026R01S5,marshal_sector,18,,5941.144531,-5404.362305,-75.434627,4274.234549
52,Y2026R01S5,marshal_sector,19,,3919.878418,-3964.581055,29.374457,4552.800388
53,Y2026R01S5,marshal_sector,20,,2894.992920,-4280.795410,-50.094360,4701.184036

In [210]:
import pandas as pd
pd.DataFrame(circuit_features)

,0,1,2,3,4,5,6,7,8
0,Y2026R01S5,corner,1,,44.0,-3650.594482,1193.784180,-176.632730,353.883741
1,Y2026R01S5,corner,2,,44.0,-3555.053223,1992.750244,-1.517007,436.700337
2,Y2026R01S5,corner,3,,44.0,-7194.970215,7101.942383,162.258315,1082.289274
3,Y2026R01S5,corner,4,,44.0,-5878.734375,7709.864746,-23.426263,1240.170991
4,Y2026R01S5,corner,5,,44.0,-5870.662598,9676.805664,159.215959,1435.149386
5,Y2026R01S5,corner,6,,44.0,-2280.641357,11861.559570,96.736266,1864.705500
6,Y2026R01S5,corner,7,,44.0,-1296.382446,11398.008789,-104.065903,1987.203085
7,Y2026R01S5,corner,8,,44.0,502.412537,10576.311523,39.145642,2157.206134
8,Y2026R01S5,corner,9,,44.0,2838.843750,798.959839,-101.197334,3279.161824
9,Y2026R01S5,corner,10,,44.0,3973.896484,855.019897,73.476771,3383.648575
10,Y2026R01S5,corner,11,,44.0,7489.130859,-4851.345215,-15.779635,4087.765440
11,Y2026R01S5,corner,12,,44.0,5020.217773,-5538.887695,-106.082895,4359.092824
12,Y2026R01S5,corner,13,,44.0,3587.226562,-3634.000000,89.839297,4608.497211
13,Y2026R01S5,corner,14,,44.0,2300.284180,-4454.023438,-97.403246,4764.984350
14,Y2026R01S5,marshal_light,1,,44.0,-1200.067871,-1327.125610,-132.857283,5231.080879
15,Y2026R01S5,marshal_light,2,,44.0,-2891.360596,276.744019,-133.358423,229.342290
16,Y2026R01S5,marshal_light,3,,44.0,-3788.004395,2744.416992,35.097031,507.785019
17,Y2026R01S5,marshal_light,4,,44.0,-5157.834961,4075.304443,-135.791112,721.059425
18,Y2026R01S5,marshal_light,5,,44.0,-6885.134766,6285.975586,-146.392665,996.258358
19,Y2026R01S5,marshal_light,6,,44.0,-6320.723145,7395.816895,-73.566602,1175.728955
20,Y2026R01S5,marshal_light,7,,44.0,-5947.000000,9210.094727,-177.905505,1371.673679
21,Y2026R01S5,marshal_light,8,,44.0,-4926.849121,10590.990234,122.445109,1568.623102
22,Y2026R01S5,marshal_light,9,,44.0,-3474.698242,11290.357422,113.415767,1716.260427
23,Y2026R01S5,marshal_light,10,,44.0,-504.105743,11226.028320,74.131091,2046.261061
24,Y2026R01S5,marshal_light,11,,44.0,1149.624146,8755.153320,7.053658,2380.257092
25,Y2026R01S5,marshal_light,12,,44.0,494.332825,5779.241211,154.510411,2685.061322
26,Y2026R01S5,marshal_light,13,,44.0,406.413727,3616.448486,-166.116110,2883.863172
27,Y2026R01S5,marshal_light,14,,44.0,1989.657959,1349.301636,-129.506926,3154.730686
28,Y2026R01S5,marshal_light,15,,44.0,3527.994629,848.884521,91.527126,3341.646954
29,Y2026R01S5,marshal_light,16,,44.0,6420.017090,-1352.264893,29.399328,3716.043495
30,Y2026R01S5,marshal_light,17,,44.0,7195.363770,-3446.331055,18.130106,3953.442346
31,Y2026R01S5,marshal_light,18,,44.0,6079.745117,-5367.668457,-74.968594,4258.121615
32,Y2026R01S5,marshal_light,19,,44.0,3962.527588,-4043.965332,27.309108,4552.800388
33,Y2026R01S5,marshal_light,20,,44.0,2935.000000,-4245.717285,-43.691578,4701.184036
34,Y2026R01S5,marshal_sector,1,,44.0,-1185.000000,-1341.000000,-128.917932,5231.080879
35,Y2026R01S5,marshal_sector,2,,44.0,-2897.316162,282.370392,-133.397702,229.342290
36,Y2026R01S5,marshal_sector,3,,44.0,-3816.246826,2784.653076,34.946842,535.144340
37,Y2026R01S5,marshal_sector,4,,44.0,-5106.551758,4022.321289,-136.082329,703.956746
38,Y2026R01S5,marshal_sector,5,,44.0,-6851.272949,6234.699219,-146.255169,984.416789
39,Y2026R01S5,marshal_sector,6,,44.0,-6348.359375,7388.174805,-75.580255,1175.728955
40,Y2026R01S5,marshal_sector,7,,44.0,-5947.000000,9210.094727,179.879527,1371.673679
41,Y2026R01S5,marshal_sector,8,,44.0,-4930.307129,10588.793945,123.768116,1568.623102
42,Y2026R01S5,marshal_sector,9,,44.0,-3455.983643,11298.679688,114.643064,1716.260427
43,Y2026R01S5,marshal_sector,10,,44.0,-375.090179,11185.664062,72.486372,2058.052363
44,Y2026R01S5,marshal_sector,11,,44.0,1152.093262,8734.820312,6.960332,2380.257092
45,Y2026R01S5,marshal_sector,12,,44.0,531.935913,5861.136230,155.920379,2649.161618
46,Y2026R01S5,marshal_sector,13,,44.0,381.896729,3724.301514,-167.228995,2883.863172
47,Y2026R01S5,marshal_sector,14,,44.0,2043.370483,1304.975830,-129.640054,3184.055466
48,Y2026R01S5,marshal_sector,15,,44.0,3740.939697,854.520142,91.479083,3364.021545
49,Y2026R01S5,marshal_sector,16,,44.0,6430.112305,-1370.088989,29.552476,3716.043495
50,Y2026R01S5,marshal_sector,17,,44.0,7169.928223,-3368.449707,18.113525,3935.990397
51,Y2026R01S5,marshal_sector,18,,44.0,5941.144531,-5404.362305,-75.434627,4274.234549
52,Y2026R01S5,marshal_sector,19,,44.0,3919.878418,-3964.581055,29.374457,4552.800388
53,Y2026R01S5,marshal_sector,20,,44.0,2894.992920,-4280.795410,-50.094360,4701.184036

In [217]:
session.car_data

{'12':                          Date  RPM  Speed  nGear  Throttle  Brake  DRS Source  \
 0     2026-05-24 19:08:02.716  0.0    0.0      0       0.0  False    0    car
 1     2026-05-24 19:08:03.036  0.0    0.0      0       0.0  False    0    car
 2     2026-05-24 19:08:03.316  0.0    0.0      0       0.0  False    0    car
 3     2026-05-24 19:08:03.516  0.0    0.0      0       0.0  False    0    car
 4     2026-05-24 19:08:03.716  0.0    0.0      0       0.0  False    0    car
 ...                       ...  ...    ...    ...       ...    ...  ...    ...
 34522 2026-05-24 21:42:39.910  0.0    0.0      0     104.0   True    0    car
 34523 2026-05-24 21:42:40.150  0.0    0.0      0     104.0   True    0    car
 34524 2026-05-24 21:42:40.429  0.0    0.0      0     104.0   True    0    car
 34525 2026-05-24 21:42:40.629  0.0    0.0      0     104.0   True    0    car
 34526 2026-05-24 21:42:40.829  0.0    0.0      0     104.0   True    0    car

                         Time            SessionTime
 0     0 days 00:00:47.242000 0 days 00:00:47.242000
 1     0 days 00:00:47.562000 0 days 00:00:47.562000
 2     0 days 00:00:47.842000 0 days 00:00:47.842000
 3     0 days 00:00:48.042000 0 days 00:00:48.042000
 4     0 days 00:00:48.242000 0 days 00:00:48.242000
 ...                      ...                    ...
 34522 0 days 02:35:24.436000 0 days 02:35:24.436000
 34523 0 days 02:35:24.676000 0 days 02:35:24.676000
 34524 0 days 02:35:24.955000 0 days 02:35:24.955000
 34525 0 days 02:35:25.155000 0 days 02:35:25.155000
 34526 0 days 02:35:25.355000 0 days 02:35:25.355000

 [34527 rows x 10 columns],
 '44':                          Date  RPM  Speed  nGear  Throttle  Brake  DRS Source  \
 0     2026-05-24 19:08:02.716  0.0    0.0      0       0.0  False    0    car
 1     2026-05-24 19:08:03.036  0.0    0.0      0       0.0  False    0    car
 2     2026-05-24 19:08:03.316  0.0    0.0      0       0.0  False    0    car
 3     2026-05-24 19:08:03.516  0.0    0.0      0       0.0  False    0    car
 4     2026-05-24 19:08:03.716  0.0    0.0      0       0.0  False    0    car
 ...                       ...  ...    ...    ...       ...    ...  ...    ...
 34522 2026-05-24 21:42:39.910  0.0    0.0      0       0.0  False    0    car
 34523 2026-05-24 21:42:40.150  0.0    0.0      0       0.0  False    0    car
 34524 2026-05-24 21:42:40.429  0.0    0.0      0       0.0  False    0    car
 34525 2026-05-24 21:42:40.629  0.0    0.0      0       0.0  False    0    car
 34526 2026-05-24 21:42:40.829  0.0    0.0      0       0.0  False    0    car

                         Time            SessionTime
 0     0 days 00:00:47.242000 0 days 00:00:47.242000
 1     0 days 00:00:47.562000 0 days 00:00:47.562000
 2     0 days 00:00:47.842000 0 days 00:00:47.842000
 3     0 days 00:00:48.042000 0 days 00:00:48.042000
 4     0 days 00:00:48.242000 0 days 00:00:48.242000
 ...                      ...                    ...
 34522 0 days 02:35:24.436000 0 days 02:35:24.436000
 34523 0 days 02:35:24.676000 0 days 02:35:24.676000
 34524 0 days 02:35:24.955000 0 days 02:35:24.955000
 34525 0 days 02:35:25.155000 0 days 02:35:25.155000
 34526 0 days 02:35:25.355000 0 days 02:35:25.355000

 [34527 rows x 10 columns],
 '3':                          Date  RPM  Speed  nGear  Throttle  Brake  DRS Source  \
 0     2026-05-24 19:08:02.716  0.0    0.0      0       0.0  False    0    car
 1     2026-05-24 19:08:03.036  0.0    0.0      0       0.0  False    0    car
 2     2026-05-24 19:08:03.316  0.0    0.0      0       0.0  False    0    car
 3     2026-05-24 19:08:03.516  0.0    0.0      0       0.0  False    0    car
 4     2026-05-24 19:08:03.716  0.0    0.0      0       0.0  False    0    car
 ...                       ...  ...    ...    ...       ...    ...  ...    ...
 34522 2026-05-24 21:42:39.910  0.0    0.0      0     104.0   True    0    car
 34523 2026-05-24 21:42:40.150  0.0    0.0      0     104.0   True    0    car
 34524 2026-05-24 21:42:40.429  0.0    0.0      0     104.0   True    0    car
 34525 2026-05-24 21:42:40.629  0.0    0.0      0     104.0   True    0    car
 34526 2026-05-24 21:42:40.829  0.0    0.0      0     104.0   True    0    car

                         Time            SessionTime
 0     0 days 00:00:47.242000 0 days 00:00:47.242000
 1     0 days 00:00:47.562000 0 days 00:00:47.562000
 2     0 days 00:00:47.842000 0 days 00:00:47.842000
 3     0 days 00:00:48.042000 0 days 00:00:48.042000
 4     0 days 00:00:48.242000 0 days 00:00:48.242000
 ...                      ...                    ...
 34522 0 days 02:35:24.436000 0 days 02:35:24.436000
 34523 0 days 02:35:24.676000 0 days 02:35:24.676000
 34524 0 days 02:35:24.955000 0 days 02:35:24.955000
 34525 0 days 02:35:25.155000 0 days 02:35:25.155000
 34526 0 days 02:35:25.355000 0 days 02:35:25.355000

 [34527 rows x 10 columns],
 '16':                          Date  RPM  Speed  nGear  Throttle  Brake  DRS Source  \
 0     2026-05-24 19:08:02.716  0.0    0.0      0       0.0  False    0    car
 1     2026-05-24 19:08:03.036  0.0    0.0      0       0.0  False    0    car
 2     2026-05-24 19:08:03.316  0.0    0.0      0       0.0  False    0    car
 3     2026-05-24 19:08:03.516  0.0    0.0      0       0.0  False    0    car
 4     2026-05-24 19:08:03.716  0.0    0.0      0       0.0  False    0    car
 ...                       ...  ...    ...    ...       ...    ...  ...    ...
 34522 2026-05-24 21:42:39.910  0.0    0.0      0       0.0  False    0    car
 34523 2026-05-24 21:42:40.150  0.0    0.0      0       0.0  False    0    car
 34524 2026-05-24 21:42:40.429  0.0    0.0      0       0.0  False    0    car
 34525 2026-05-24 21:42:40.629  0.0    0.0      0       0.0  False    0    car
 34526 2026-05-24 21:42:40.829  0.0    0.0      0       0.0  False    0    car

                         Time            SessionTime
 0     0 days 00:00:47.242000 0 days 00:00:47.242000
 1     0 days 00:00:47.562000 0 days 00:00:47.562000
 2     0 days 00:00:47.842000 0 days 00:00:47.842000
 3     0 days 00:00:48.042000 0 days 00:00:48.042000
 4     0 days 00:00:48.242000 0 days 00:00:48.242000
 ...                      ...                    ...
 34522 0 days 02:35:24.436000 0 days 02:35:24.436000
 34523 0 days 02:35:24.676000 0 days 02:35:24.676000
 34524 0 days 02:35:24.955000 0 days 02:35:24.955000
 34525 0 days 02:35:25.155000 0 days 02:35:25.155000
 34526 0 days 02:35:25.355000 0 days 02:35:25.355000

 [34527 rows x 10 columns],
 '6':                          Date    RPM  Speed  nGear  Throttle  Brake  DRS  \
 0     2026-05-24 19:08:02.716    0.0    0.0      0       0.0  False    0
 1     2026-05-24 19:08:03.036    0.0    0.0      0       0.0  False    0
 2     2026-05-24 19:08:03.316    0.0    0.0      0       0.0  False    0
 3     2026-05-24 19:08:03.516    0.0    0.0      0       0.0  False    0
 4     2026-05-24 19:08:03.716  560.0    0.0      0       0.0  False    0
 ...                       ...    ...    ...    ...       ...    ...  ...
 34522 2026-05-24 21:42:39.910    0.0    0.0      0     104.0   True    0
 34523 2026-05-24 21:42:40.150    0.0    0.0      0     104.0   True    0
 34524 2026-05-24 21:42:40.429    0.0    0.0      0     104.0   True    0
 34525 2026-05-24 21:42:40.629    0.0    0.0      0     104.0   True    0
 34526 2026-05-24 21:42:40.829    0.0    0.0      0     104.0   True    0

       Source                   Time            SessionTime
 0        car 0 days 00:00:47.242000 0 days 00:00:47.242000
 1        car 0 days 00:00:47.562000 0 days 00:00:47.562000
 2        car 0 days 00:00:47.842000 0 days 00:00:47.842000
 3        car 0 days 00:00:48.042000 0 days 00:00:48.042000
 4        car 0 days 00:00:48.242000 0 days 00:00:48.242000
 ...      ...                    ...                    ...
 34522    car 0 days 02:35:24.436000 0 days 02:35:24.436000
 34523    car 0 days 02:35:24.676000 0 days 02:35:24.676000
 34524    car 0 days 02:35:24.955000 0 days 02:35:24.955000
 34525    car 0 days 02:35:25.155000 0 days 02:35:25.155000
 34526    car 0 days 02:35:25.355000 0 days 02:35:25.355000

 [34527 rows x 10 columns],
 '43':                          Date  RPM  Speed  nGear  Throttle  Brake  DRS Source  \
 0     2026-05-24 19:08:02.716  0.0    0.0      0       0.0  False    0    car
 1     2026-05-24 19:08:03.036  0.0    0.0      0       0.0  False    0    car
 2     2026-05-24 19:08:03.316  0.0    0.0      0       0.0  False    0    car
 3     2026-05-24 19:08:03.516  0.0    0.0      0       0.0  False    0    car
 4     2026-05-24 19:08:03.716  0.0    0.0      0       0.0  False    0    car
 ...                       ...  ...    ...    ...       ...    ...  ...    ...
 34522 2026-05-24 21:42:39.910  0.0    0.0      0     104.0   True    0    car
 34523 2026-05-24 21:42:40.150  0.0    0.0      0     104.0   True    0    car
 34524 2026-05-24 21:42:40.429  0.0    0.0      0     104.0   True    0    car
 34525 2026-05-24 21:42:40.629  0.0    0.0      0     104.0   True    0    car
 34526 2026-05-24 21:42:40.829  0.0    0.0      0     104.0   True    0    car

                         Time            SessionTime
 0     0 days 00:00:47.242000 0 days 00:00:47.242000
 1     0 days 00:00:47.562000 0 days 00:00:47.562000
 2     0 days 00:00:47.842000 0 days 00:00:47.842000
 3     0 days 00:00:48.042000 0 days 00:00:48.042000
 4     0 days 00:00:48.242000 0 days 00:00:48.242000
 ...                      ...                    ...
 34522 0 days 02:35:24.436000 0 days 02:35:24.436000
 34523 0 days 02:35:24.676000 0 days 02:35:24.676000
 34524 0 days 02:35:24.955000 0 days 02:35:24.955000
 34525 0 days 02:35:25.155000 0 days 02:35:25.155000
 34526 0 days 02:35:25.355000 0 days 02:35:25.355000

 [34527 rows x 10 columns],
 '30':                          Date  RPM  Speed  nGear  Throttle  Brake  DRS Source  \
 0     2026-05-24 19:08:02.716  0.0    0.0      0       0.0  False    0    car
 1     2026-05-24 19:08:03.036  0.0    0.0      0       0.0  False    0    car
 2     2026-05-24 19:08:03.316  0.0    0.0      0       0.0  False    0    car
 3     2026-05-24 19:08:03.516  0.0    0.0      0       0.0  False    0    car
 4     2026-05-24 19:08:03.716  0.0    0.0      0       0.0  False    0    car
 ...                       ...  ...    ...    ...       ...    ...  ...    ...
 34522 2026-05-24 21:42:39.910  0.0    0.0      0     104.0   True    0    car
 34523 2026-05-24 21:42:40.150  0.0    0.0      0     104.0   True    0    car
 34524 2026-05-24 21:42:40.429  0.0    0.0      0     104.0   True    0    car
 34525 2026-05-24 21:42:40.629  0.0    0.0      0     104.0   True    0    car
 34526 2026-05-24 21:42:40.829  0.0    0.0      0     104.0   True    0    car

                         Time            SessionTime
 0     0 days 00:00:47.242000 0 days 00:00:47.242000
 1     0 days 00:00:47.562000 0 days 00:00:47.562000
 2     0 days 00:00:47.842000 0 days 00:00:47.842000
 3     0 days 00:00:48.042000 0 days 00:00:48.042000
 4     0 days 00:00:48.242000 0 days 00:00:48.242000
 ...                      ...                    ...
 34522 0 days 02:35:24.436000 0 days 02:35:24.436000
 34523 0 days 02:35:24.676000 0 days 02:35:24.676000
 34524 0 days 02:35:24.955000 0 days 02:35:24.955000
 34525 0 days 02:35:25.155000 0 days 02:35:25.155000
 34526 0 days 02:35:25.355000 0 days 02:35:25.355000

 [34527 rows x 10 columns],
 '10':                          Date  RPM  Speed  nGear  Throttle  Brake  DRS Source  \
 0     2026-05-24 19:08:02.716  0.0    0.0      0       0.0  False    0    car
 1     2026-05-24 19:08:03.036  0.0    0.0      0       0.0  False    0    car
 2     2026-05-24 19:08:03.316  0.0    0.0      0       0.0  False    0    car
 3     2026-05-24 19:08:03.516  0.0    0.0      0       0.0  False    0    car
 4     2026-05-24 19:08:03.716  0.0    0.0      0       0.0  False    0    car
 ...                       ...  ...    ...    ...       ...    ...  ...    ...
 34522 2026-05-24 21:42:39.910  0.0    0.0      0     104.0   True    0    car
 34523 2026-05-24 21:42:40.150  0.0    0.0      0     104.0   True    0    car
 34524 2026-05-24 21:42:40.429  0.0    0.0      0     104.0   True    0    car
 34525 2026-05-24 21:42:40.629  0.0    0.0      0     104.0   True    0    car
 34526 2026-05-24 21:42:40.829  0.0    0.0      0     104.0   True    0    car

                         Time            SessionTime
 0     0 days 00:00:47.242000 0 days 00:00:47.242000
 1     0 days 00:00:47.562000 0 days 00:00:47.562000
 2     0 days 00:00:47.842000 0 days 00:00:47.842000
 3     0 days 00:00:48.042000 0 days 00:00:48.042000
 4     0 days 00:00:48.242000 0 days 00:00:48.242000
 ...                      ...                    ...
 34522 0 days 02:35:24.436000 0 days 02:35:24.436000
 34523 0 days 02:35:24.676000 0 days 02:35:24.676000
 34524 0 days 02:35:24.955000 0 days 02:35:24.955000
 34525 0 days 02:35:25.155000 0 days 02:35:25.155000
 34526 0 days 02:35:25.355000 0 days 02:35:25.355000

 [34527 rows x 10 columns],
 '55':                          Date  RPM  Speed  nGear  Throttle  Brake  DRS Source  \
 0     2026-05-24 19:08:02.716  0.0    0.0      0       0.0  False    0    car
 1     2026-05-24 19:08:03.036  0.0    0.0      0       0.0  False    0    car
 2     2026-05-24 19:08:03.316  0.0    0.0      0       0.0  False    0    car
 3     2026-05-24 19:08:03.516  0.0    0.0      0       0.0  False    0    car
 4     2026-05-24 19:08:03.716  0.0    0.0      0       0.0  False    0    car
 ...                       ...  ...    ...    ...       ...    ...  ...    ...
 34522 2026-05-24 21:42:39.910  0.0    0.0      0       0.0  False    0    car
 34523 2026-05-24 21:42:40.150  0.0    0.0      0       0.0  False    0    car
 34524 2026-05-24 21:42:40.429  0.0    0.0      0       0.0  False    0    car
 34525 2026-05-24 21:42:40.629  0.0    0.0      0       0.0  False    0    car
 34526 2026-05-24 21:42:40.829  0.0    0.0      0       0.0  False    0    car

                         Time            SessionTime
 0     0 days 00:00:47.242000 0 days 00:00:47.242000
 1     0 days 00:00:47.562000 0 days 00:00:47.562000
 2     0 days 00:00:47.842000 0 days 00:00:47.842000
 3     0 days 00:00:48.042000 0 days 00:00:48.042000
 4     0 days 00:00:48.242000 0 days 00:00:48.242000
 ...                      ...                    ...
 34522 0 days 02:35:24.436000 0 days 02:35:24.436000
 34523 0 days 02:35:24.676000 0 days 02:35:24.676000
 34524 0 days 02:35:24.955000 0 days 02:35:24.955000
 34525 0 days 02:35:25.155000 0 days 02:35:25.155000
 34526 0 days 02:35:25.355000 0 days 02:35:25.355000

 [34527 rows x 10 columns],
 '87':                          Date  RPM  Speed  nGear  Throttle  Brake  DRS Source  \
 0     2026-05-24 19:08:02.716  0.0    0.0      0       0.0  False    0    car
 1     2026-05-24 19:08:03.036  0.0    0.0      0       0.0  False    0    car
 2     2026-05-24 19:08:03.316  0.0    0.0      0       0.0  False    0    car
 3     2026-05-24 19:08:03.516  0.0    0.0      0       0.0  False    0    car
 4     2026-05-24 19:08:03.716  0.0    0.0      0       0.0  False    0    car
 ...                       ...  ...    ...    ...       ...    ...  ...    ...
 34522 2026-05-24 21:42:39.910  0.0    0.0      0       0.0  False    0    car
 34523 2026-05-24 21:42:40.150  0.0    0.0      0       0.0  False    0    car
 34524 2026-05-24 21:42:40.429  0.0    0.0      0       0.0  False    0    car
 34525 2026-05-24 21:42:40.629  0.0    0.0      0       0.0  False    0    car
 34526 2026-05-24 21:42:40.829  0.0    0.0      0       0.0  False    0    car

                         Time            SessionTime
 0     0 days 00:00:47.242000 0 days 00:00:47.242000
 1     0 days 00:00:47.562000 0 days 00:00:47.562000
 2     0 days 00:00:47.842000 0 days 00:00:47.842000
 3     0 days 00:00:48.042000 0 days 00:00:48.042000
 4     0 days 00:00:48.242000 0 days 00:00:48.242000
 ...                      ...                    ...
 34522 0 days 02:35:24.436000 0 days 02:35:24.436000
 34523 0 days 02:35:24.676000 0 days 02:35:24.676000
 34524 0 days 02:35:24.955000 0 days 02:35:24.955000
 34525 0 days 02:35:25.155000 0 days 02:35:25.155000
 34526 0 days 02:35:25.355000 0 days 02:35:25.355000

 [34527 rows x 10 columns],
 '81':                          Date  RPM  Speed  nGear  Throttle  Brake  DRS Source  \
 0     2026-05-24 19:08:02.716  0.0    0.0      0       0.0  False    0    car
 1     2026-05-24 19:08:03.036  0.0    0.0      0       0.0  False    0    car
 2     2026-05-24 19:08:03.316  0.0    0.0      0       0.0  False    0    car
 3     2026-05-24 19:08:03.516  0.0    0.0      0       0.0  False    0    car
 4     2026-05-24 19:08:03.716  0.0    0.0      0       0.0  False    0    car
 ...                       ...  ...    ...    ...       ...    ...  ...    ...
 34522 2026-05-24 21:42:39.910  0.0    0.0      0     104.0   True    0    car
 34523 2026-05-24 21:42:40.150  0.0    0.0      0     104.0   True    0    car
 34524 2026-05-24 21:42:40.429  0.0    0.0      0     104.0   True    0    car
 34525 2026-05-24 21:42:40.629  0.0    0.0      0     104.0   True    0    car
 34526 2026-05-24 21:42:40.829  0.0    0.0      0     104.0   True    0    car

                         Time            SessionTime
 0     0 days 00:00:47.242000 0 days 00:00:47.242000
 1     0 days 00:00:47.562000 0 days 00:00:47.562000
 2     0 days 00:00:47.842000 0 days 00:00:47.842000
 3     0 days 00:00:48.042000 0 days 00:00:48.042000
 4     0 days 00:00:48.242000 0 days 00:00:48.242000
 ...                      ...                    ...
 34522 0 days 02:35:24.436000 0 days 02:35:24.436000
 34523 0 days 02:35:24.676000 0 days 02:35:24.676000
 34524 0 days 02:35:24.955000 0 days 02:35:24.955000
 34525 0 days 02:35:25.155000 0 days 02:35:25.155000
 34526 0 days 02:35:25.355000 0 days 02:35:25.355000

 [34527 rows x 10 columns],
 '27':                          Date  RPM  Speed  nGear  Throttle  Brake  DRS Source  \
 0     2026-05-24 19:08:02.716  0.0    0.0      0       0.0  False    0    car
 1     2026-05-24 19:08:03.036  0.0    0.0      0       0.0  False    0    car
 2     2026-05-24 19:08:03.316  0.0    0.0      0       0.0  False    0    car
 3     2026-05-24 19:08:03.516  0.0    0.0      0       0.0  False    0    car
 4     2026-05-24 19:08:03.716  0.0    0.0      0       0.0  False    0    car
 ...                       ...  ...    ...    ...       ...    ...  ...    ...
 34522 2026-05-24 21:42:39.910  0.0    0.0      0     104.0   True    0    car
 34523 2026-05-24 21:42:40.150  0.0    0.0      0     104.0   True    0    car
 34524 2026-05-24 21:42:40.429  0.0    0.0      0     104.0   True    0    car
 34525 2026-05-24 21:42:40.629  0.0    0.0      0     104.0   True    0    car
 34526 2026-05-24 21:42:40.829  0.0    0.0      0     104.0   True    0    car

                         Time            SessionTime
 0     0 days 00:00:47.242000 0 days 00:00:47.242000
 1     0 days 00:00:47.562000 0 days 00:00:47.562000
 2     0 days 00:00:47.842000 0 days 00:00:47.842000
 3     0 days 00:00:48.042000 0 days 00:00:48.042000
 4     0 days 00:00:48.242000 0 days 00:00:48.242000
 ...                      ...                    ...
 34522 0 days 02:35:24.436000 0 days 02:35:24.436000
 34523 0 days 02:35:24.676000 0 days 02:35:24.676000
 34524 0 days 02:35:24.955000 0 days 02:35:24.955000
 34525 0 days 02:35:25.155000 0 days 02:35:25.155000
 34526 0 days 02:35:25.355000 0 days 02:35:25.355000

 [34527 rows x 10 columns],
 '5':                          Date  RPM  Speed  nGear  Throttle  Brake  DRS Source  \
 0     2026-05-24 19:08:02.716  0.0    0.0      0       0.0  False    0    car
 1     2026-05-24 19:08:03.036  0.0    0.0      0       0.0  False    0    car
 2     2026-05-24 19:08:03.316  0.0    0.0      0       0.0  False    0    car
 3     2026-05-24 19:08:03.516  0.0    0.0      0       0.0  False    0    car
 4     2026-05-24 19:08:03.716  0.0    0.0      0       0.0  False    0    car

In [218]:
session.pos_data['12']

,Date,Status,X,Y,Z,Source,Time,SessionTime
0,2026-05-24 19:07:27.964,OnTrack,0.0,0.0,0.0,pos,0 days 00:00:12.490000,0 days 00:00:12.490000
1,2026-05-24 19:07:28.444,OnTrack,0.0,0.0,0.0,pos,0 days 00:00:12.970000,0 days 00:00:12.970000
2,2026-05-24 19:07:28.604,OnTrack,0.0,0.0,0.0,pos,0 days 00:00:13.130000,0 days 00:00:13.130000
3,2026-05-24 19:07:29.044,OnTrack,0.0,0.0,0.0,pos,0 days 00:00:13.570000,0 days 00:00:13.570000
4,2026-05-24 19:07:29.204,OnTrack,0.0,0.0,0.0,pos,0 days 00:00:13.730000,0 days 00:00:13.730000
...,...,...,...,...,...,...,...,...
35316,2026-05-24 21:43:01.468,OnTrack,3423.0,971.0,130.0,pos,0 days 02:35:45.994000,0 days 02:35:45.994000
35317,2026-05-24 21:43:01.708,OnTrack,3423.0,971.0,130.0,pos,0 days 02:35:46.234000,0 days 02:35:46.234000
35318,2026-05-24 21:43:01.748,OnTrack,3423.0,971.0,130.0,pos,0 days 02:35:46.274000,0 days 02:35:46.274000
35319,2026-05-24 21:43:01.988,OnTrack,3423.0,971.0,130.0,pos,0 days 02:35:46.514000,0 days 02:35:46.514000
35320,2026-05-24 21:43:02.188,OnTrack,3423.0,971.0,130.0,pos,0 days 02:35:46.714000,0 days 02:35:46.714000

In [232]:
with psycopg.connect(database_url) as conn:
    with conn.cursor() as cur:
        cur.execute(f'select * from position_data  ; ')
        position_data = cur.fetchall()
len(position_data)

707058

In [233]:
with psycopg.connect(database_url) as conn:
    with conn.cursor() as cur:
        cur.execute(f'select * from telemetry_data  ; ')
        telemetry_data = cur.fetchall()
len(telemetry_data)

685938

In [236]:
pd.DataFrame(telemetry_data[:]).sample(n=20)

,0,1,2,3,4,5,6,7,8,9,10,11
560605,Y2026R01S5,14,8679.004,2026-03-08 05:25:45.627000+00:00,8679.004,car,0.0,0.0,0.0,104.0,1.0,0.0
141009,Y2026R01S5,1,4827.872,2026-03-08 04:21:34.495000+00:00,4827.872,car,11318.0,204.0,5.0,22.0,0.0,0.0
512825,Y2026R01S5,18,4195.830,2026-03-08 04:11:02.453000+00:00,4195.830,car,10790.0,279.0,7.0,100.0,0.0,0.0
585928,Y2026R01S5,77,7101.159,2026-03-08 04:59:27.782000+00:00,7101.159,car,0.0,0.0,0.0,104.0,1.0,0.0
144907,Y2026R01S5,1,5884.671,2026-03-08 04:39:11.294000+00:00,5884.671,car,10150.0,280.0,8.0,100.0,0.0,0.0
659410,Y2026R01S5,27,1696.101,2026-03-08 03:29:22.724000+00:00,1696.101,car,4028.0,26.0,3.0,0.0,0.0,0.0
314109,Y2026R01S5,31,1072.900,2026-03-08 03:18:59.523000+00:00,1072.900,car,3551.0,0.0,0.0,0.0,0.0,0.0
91197,Y2026R01S5,16,8214.802,2026-03-08 05:18:01.425000+00:00,8214.802,car,10800.0,274.0,7.0,100.0,0.0,0.0
275069,Y2026R01S5,5,7344.479,2026-03-08 05:03:31.102000+00:00,7344.479,car,11307.0,308.0,7.0,100.0,0.0,0.0
644739,Y2026R01S5,81,6143.271,2026-03-08 04:43:29.894000+00:00,6143.271,car,0.0,0.0,0.0,104.0,1.0,0.0
319445,Y2026R01S5,31,2502.585,2026-03-08 03:42:49.208000+00:00,2502.585,car,0.0,0.0,0.0,0.0,0.0,0.0
402707,Y2026R01S5,30,8137.001,2026-03-08 05:16:43.624000+00:00,8137.001,car,11525.0,246.0,6.0,100.0,0.0,0.0
667297,Y2026R01S5,27,3821.988,2026-03-08 04:04:48.611000+00:00,3821.988,car,0.0,0.0,0.0,104.0,1.0,0.0
572527,Y2026R01S5,77,3488.828,2026-03-08 03:59:15.451000+00:00,3488.828,car,3433.0,0.0,0.0,0.0,0.0,0.0
366268,Y2026R01S5,23,6721.556,2026-03-08 04:53:08.179000+00:00,6721.556,car,8925.0,80.0,1.0,50.0,0.0,0.0
609652,Y2026R01S5,6,5083.432,2026-03-08 04:25:50.055000+00:00,5083.432,car,0.0,0.0,6.0,0.0,0.0,0.0
421374,Y2026R01S5,43,4761.871,2026-03-08 04:20:28.494000+00:00,4761.871,car,9821.0,200.0,5.0,0.0,0.0,0.0
289000,Y2026R01S5,10,2702.305,2026-03-08 03:46:08.928000+00:00,2702.305,car,0.0,0.0,0.0,0.0,0.0,0.0
29232,Y2026R01S5,63,8323.443,2026-03-08 05:19:50.066000+00:00,8323.443,car,10983.0,285.0,7.0,100.0,0.0,0.0
160620,Y2026R01S5,3,1716.341,2026-03-08 03:29:42.964000+00:00,1716.341,car,10772.0,301.0,8.0,100.0,0.0,0.0

In [225]:
len(position_data)

400466

In [226]:
pd.DataFrame(position_data)

,0,1,2,3,4,5,6,7,8,9
0,Y2026R01S1,1,71.255,2026-03-06 01:16:11.267000+00:00,71.255,OnTrack,pos,0.0,0.0,0.0
1,Y2026R01S1,1,71.425,2026-03-06 01:16:11.437000+00:00,71.425,OnTrack,pos,0.0,0.0,0.0
2,Y2026R01S1,1,71.615,2026-03-06 01:16:11.627000+00:00,71.615,OnTrack,pos,0.0,0.0,0.0
3,Y2026R01S1,1,72.005,2026-03-06 01:16:12.017000+00:00,72.005,OnTrack,pos,0.0,0.0,0.0
4,Y2026R01S1,1,72.175,2026-03-06 01:16:12.187000+00:00,72.175,OnTrack,pos,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
400461,Y2026R01S1,87,4896.586,2026-03-06 02:36:36.598000+00:00,4896.586,OnTrack,pos,22.0,-2308.0,82.0
400462,Y2026R01S1,87,4896.896,2026-03-06 02:36:36.908000+00:00,4896.896,OnTrack,pos,22.0,-2308.0,82.0
400463,Y2026R01S1,87,4897.226,2026-03-06 02:36:37.238000+00:00,4897.226,OnTrack,pos,22.0,-2308.0,82.0
400464,Y2026R01S1,87,4897.426,2026-03-06 02:36:37.438000+00:00,4897.426,OnTrack,pos,22.0,-2308.0,82.0
400465,Y2026R01S1,87,4897.725,2026-03-06 02:36:37.737000+00:00,4897.725,OnTrack,pos,22.0,-2308.0,82.0

In [230]:
float(session.car_data['1'].iloc[0]['Brake'])

0.0

In [231]:
session.car_data['1']

,Date,RPM,Speed,nGear,Throttle,Brake,DRS,Source,Time,SessionTime
0,2026-05-24 19:08:02.716,0.0,0.0,0,0.0,False,0,car,0 days 00:00:47.242000,0 days 00:00:47.242000
1,2026-05-24 19:08:03.036,0.0,0.0,0,0.0,False,0,car,0 days 00:00:47.562000,0 days 00:00:47.562000
2,2026-05-24 19:08:03.316,0.0,0.0,0,0.0,False,0,car,0 days 00:00:47.842000,0 days 00:00:47.842000
3,2026-05-24 19:08:03.516,0.0,0.0,0,0.0,False,0,car,0 days 00:00:48.042000,0 days 00:00:48.042000
4,2026-05-24 19:08:03.716,0.0,0.0,0,0.0,False,0,car,0 days 00:00:48.242000,0 days 00:00:48.242000
...,...,...,...,...,...,...,...,...,...,...
34522,2026-05-24 21:42:39.910,0.0,0.0,0,104.0,True,0,car,0 days 02:35:24.436000,0 days 02:35:24.436000
34523,2026-05-24 21:42:40.150,0.0,0.0,0,104.0,True,0,car,0 days 02:35:24.676000,0 days 02:35:24.676000
34524,2026-05-24 21:42:40.429,0.0,0.0,0,104.0,True,0,car,0 days 02:35:24.955000,0 days 02:35:24.955000
34525,2026-05-24 21:42:40.629,0.0,0.0,0,104.0,True,0,car,0 days 02:35:25.155000,0 days 02:35:25.155000
34526,2026-05-24 21:42:40.829,0.0,0.0,0,104.0,True,0,car,0 days 02:35:25.355000,0 days 02:35:25.355000

In [237]:
session._session_split_times

[datetime.timedelta(0), datetime.timedelta(days=1), datetime.timedelta(days=1)]

In [ ]:
ses